// Code generated by ent, DO NOT EDIT.

package tunneltrafficlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tunneltrafficlog type in the database.
	Label = "tunnel_traffic_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTunnelID holds the string denoting the tunnel_id field in the database.
	FieldTunnelID = "tunnel_id"
	// FieldBytesIn holds the string denoting the bytes_in field in the database.
	FieldBytesIn = "bytes_in"
	// FieldBytesOut holds the string denoting the bytes_out field in the database.
	FieldBytesOut = "bytes_out"
	// FieldTotalRequests holds the string denoting the total_requests field in the database.
	FieldTotalRequests = "total_requests"
	// FieldRecordedAt holds the string denoting the recorded_at field in the database.
	FieldRecordedAt = "recorded_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the tunneltrafficlog in the database.
	Table = "tunnel_traffic_logs"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "tunnel_traffic_logs"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_traffic_logs"
)

// Columns holds all SQL columns for tunneltrafficlog fields.
var Columns = []string{
	FieldID,
	FieldTunnelID,
	FieldBytesIn,
	FieldBytesOut,
	FieldTotalRequests,
	FieldRecordedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tunnel_traffic_logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_traffic_logs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TunnelIDValidator is a validator for the "tunnel_id" field. It is called by the builders before save.
	TunnelIDValidator func(string) error
	// DefaultBytesIn holds the default value on creation for the "bytes_in" field.
	DefaultBytesIn int64
	// DefaultBytesOut holds the default value on creation for the "bytes_out" field.
	DefaultBytesOut int64
	// DefaultTotalRequests holds the default value on creation for the "total_requests" field.
	DefaultTotalRequests int64
	// DefaultRecordedAt holds the default value on creation for the "recorded_at" field.
	DefaultRecordedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the TunnelTrafficLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTunnelID orders the results by the tunnel_id field.
func ByTunnelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTunnelID, opts...).ToFunc()
}

// ByBytesIn orders the results by the bytes_in field.
func ByBytesIn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBytesIn, opts...).ToFunc()
}

// ByBytesOut orders the results by the bytes_out field.
func ByBytesOut(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBytesOut, opts...).ToFunc()
}

// ByTotalRequests orders the results by the total_requests field.
func ByTotalRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalRequests, opts...).ToFunc()
}

// ByRecordedAt orders the results by the recorded_at field.
func ByRecordedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
