// Code generated by ent, DO NOT EDIT.

package tunneltrafficlog

import (
	"cloudflared-tunnel/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLTE(FieldID, id))
}

// TunnelID applies equality check predicate on the "tunnel_id" field. It's identical to TunnelIDEQ.
func TunnelID(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldTunnelID, v))
}

// BytesIn applies equality check predicate on the "bytes_in" field. It's identical to BytesInEQ.
func BytesIn(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldBytesIn, v))
}

// BytesOut applies equality check predicate on the "bytes_out" field. It's identical to BytesOutEQ.
func BytesOut(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldBytesOut, v))
}

// TotalRequests applies equality check predicate on the "total_requests" field. It's identical to TotalRequestsEQ.
func TotalRequests(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldTotalRequests, v))
}

// RecordedAt applies equality check predicate on the "recorded_at" field. It's identical to RecordedAtEQ.
func RecordedAt(v time.Time) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldRecordedAt, v))
}

// TunnelIDEQ applies the EQ predicate on the "tunnel_id" field.
func TunnelIDEQ(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldTunnelID, v))
}

// TunnelIDNEQ applies the NEQ predicate on the "tunnel_id" field.
func TunnelIDNEQ(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNEQ(FieldTunnelID, v))
}

// TunnelIDIn applies the In predicate on the "tunnel_id" field.
func TunnelIDIn(vs ...string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldIn(FieldTunnelID, vs...))
}

// TunnelIDNotIn applies the NotIn predicate on the "tunnel_id" field.
func TunnelIDNotIn(vs ...string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNotIn(FieldTunnelID, vs...))
}

// TunnelIDGT applies the GT predicate on the "tunnel_id" field.
func TunnelIDGT(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGT(FieldTunnelID, v))
}

// TunnelIDGTE applies the GTE predicate on the "tunnel_id" field.
func TunnelIDGTE(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGTE(FieldTunnelID, v))
}

// TunnelIDLT applies the LT predicate on the "tunnel_id" field.
func TunnelIDLT(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLT(FieldTunnelID, v))
}

// TunnelIDLTE applies the LTE predicate on the "tunnel_id" field.
func TunnelIDLTE(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLTE(FieldTunnelID, v))
}

// TunnelIDContains applies the Contains predicate on the "tunnel_id" field.
func TunnelIDContains(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldContains(FieldTunnelID, v))
}

// TunnelIDHasPrefix applies the HasPrefix predicate on the "tunnel_id" field.
func TunnelIDHasPrefix(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldHasPrefix(FieldTunnelID, v))
}

// TunnelIDHasSuffix applies the HasSuffix predicate on the "tunnel_id" field.
func TunnelIDHasSuffix(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldHasSuffix(FieldTunnelID, v))
}

// TunnelIDEqualFold applies the EqualFold predicate on the "tunnel_id" field.
func TunnelIDEqualFold(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEqualFold(FieldTunnelID, v))
}

// TunnelIDContainsFold applies the ContainsFold predicate on the "tunnel_id" field.
func TunnelIDContainsFold(v string) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldContainsFold(FieldTunnelID, v))
}

// BytesInEQ applies the EQ predicate on the "bytes_in" field.
func BytesInEQ(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldBytesIn, v))
}

// BytesInNEQ applies the NEQ predicate on the "bytes_in" field.
func BytesInNEQ(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNEQ(FieldBytesIn, v))
}

// BytesInIn applies the In predicate on the "bytes_in" field.
func BytesInIn(vs ...int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldIn(FieldBytesIn, vs...))
}

// BytesInNotIn applies the NotIn predicate on the "bytes_in" field.
func BytesInNotIn(vs ...int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNotIn(FieldBytesIn, vs...))
}

// BytesInGT applies the GT predicate on the "bytes_in" field.
func BytesInGT(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGT(FieldBytesIn, v))
}

// BytesInGTE applies the GTE predicate on the "bytes_in" field.
func BytesInGTE(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGTE(FieldBytesIn, v))
}

// BytesInLT applies the LT predicate on the "bytes_in" field.
func BytesInLT(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLT(FieldBytesIn, v))
}

// BytesInLTE applies the LTE predicate on the "bytes_in" field.
func BytesInLTE(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLTE(FieldBytesIn, v))
}

// BytesOutEQ applies the EQ predicate on the "bytes_out" field.
func BytesOutEQ(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldBytesOut, v))
}

// BytesOutNEQ applies the NEQ predicate on the "bytes_out" field.
func BytesOutNEQ(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNEQ(FieldBytesOut, v))
}

// BytesOutIn applies the In predicate on the "bytes_out" field.
func BytesOutIn(vs ...int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldIn(FieldBytesOut, vs...))
}

// BytesOutNotIn applies the NotIn predicate on the "bytes_out" field.
func BytesOutNotIn(vs ...int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNotIn(FieldBytesOut, vs...))
}

// BytesOutGT applies the GT predicate on the "bytes_out" field.
func BytesOutGT(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGT(FieldBytesOut, v))
}

// BytesOutGTE applies the GTE predicate on the "bytes_out" field.
func BytesOutGTE(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGTE(FieldBytesOut, v))
}

// BytesOutLT applies the LT predicate on the "bytes_out" field.
func BytesOutLT(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLT(FieldBytesOut, v))
}

// BytesOutLTE applies the LTE predicate on the "bytes_out" field.
func BytesOutLTE(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLTE(FieldBytesOut, v))
}

// TotalRequestsEQ applies the EQ predicate on the "total_requests" field.
func TotalRequestsEQ(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldTotalRequests, v))
}

// TotalRequestsNEQ applies the NEQ predicate on the "total_requests" field.
func TotalRequestsNEQ(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNEQ(FieldTotalRequests, v))
}

// TotalRequestsIn applies the In predicate on the "total_requests" field.
func TotalRequestsIn(vs ...int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldIn(FieldTotalRequests, vs...))
}

// TotalRequestsNotIn applies the NotIn predicate on the "total_requests" field.
func TotalRequestsNotIn(vs ...int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNotIn(FieldTotalRequests, vs...))
}

// TotalRequestsGT applies the GT predicate on the "total_requests" field.
func TotalRequestsGT(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGT(FieldTotalRequests, v))
}

// TotalRequestsGTE applies the GTE predicate on the "total_requests" field.
func TotalRequestsGTE(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGTE(FieldTotalRequests, v))
}

// TotalRequestsLT applies the LT predicate on the "total_requests" field.
func TotalRequestsLT(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLT(FieldTotalRequests, v))
}

// TotalRequestsLTE applies the LTE predicate on the "total_requests" field.
func TotalRequestsLTE(v int64) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLTE(FieldTotalRequests, v))
}

// RecordedAtEQ applies the EQ predicate on the "recorded_at" field.
func RecordedAtEQ(v time.Time) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldEQ(FieldRecordedAt, v))
}

// RecordedAtNEQ applies the NEQ predicate on the "recorded_at" field.
func RecordedAtNEQ(v time.Time) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNEQ(FieldRecordedAt, v))
}

// RecordedAtIn applies the In predicate on the "recorded_at" field.
func RecordedAtIn(vs ...time.Time) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldIn(FieldRecordedAt, vs...))
}

// RecordedAtNotIn applies the NotIn predicate on the "recorded_at" field.
func RecordedAtNotIn(vs ...time.Time) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldNotIn(FieldRecordedAt, vs...))
}

// RecordedAtGT applies the GT predicate on the "recorded_at" field.
func RecordedAtGT(v time.Time) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGT(FieldRecordedAt, v))
}

// RecordedAtGTE applies the GTE predicate on the "recorded_at" field.
func RecordedAtGTE(v time.Time) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldGTE(FieldRecordedAt, v))
}

// RecordedAtLT applies the LT predicate on the "recorded_at" field.
func RecordedAtLT(v time.Time) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLT(FieldRecordedAt, v))
}

// RecordedAtLTE applies the LTE predicate on the "recorded_at" field.
func RecordedAtLTE(v time.Time) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.FieldLTE(FieldRecordedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TunnelTrafficLog) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TunnelTrafficLog) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TunnelTrafficLog) predicate.TunnelTrafficLog {
	return predicate.TunnelTrafficLog(sql.NotPredicates(p))
}
