// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/credential"
	"cloudflared-tunnel/ent/credentialtestlog"
	"cloudflared-tunnel/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CredentialTestLogUpdate is the builder for updating CredentialTestLog entities.
type CredentialTestLogUpdate struct {
	config
	hooks    []Hook
	mutation *CredentialTestLogMutation
}

// Where appends a list predicates to the CredentialTestLogUpdate builder.
func (_u *CredentialTestLogUpdate) Where(ps ...predicate.CredentialTestLog) *CredentialTestLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CredentialTestLogUpdate) SetStatus(v string) *CredentialTestLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CredentialTestLogUpdate) SetNillableStatus(v *string) *CredentialTestLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CredentialTestLogUpdate) SetErrorMessage(v string) *CredentialTestLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CredentialTestLogUpdate) SetNillableErrorMessage(v *string) *CredentialTestLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CredentialTestLogUpdate) ClearErrorMessage() *CredentialTestLogUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCredentialID sets the "credential" edge to the Credential entity by ID.
func (_u *CredentialTestLogUpdate) SetCredentialID(id int64) *CredentialTestLogUpdate {
	_u.mutation.SetCredentialID(id)
	return _u
}

// SetCredential sets the "credential" edge to the Credential entity.
func (_u *CredentialTestLogUpdate) SetCredential(v *Credential) *CredentialTestLogUpdate {
	return _u.SetCredentialID(v.ID)
}

// Mutation returns the CredentialTestLogMutation object of the builder.
func (_u *CredentialTestLogUpdate) Mutation() *CredentialTestLogMutation {
	return _u.mutation
}

// ClearCredential clears the "credential" edge to the Credential entity.
func (_u *CredentialTestLogUpdate) ClearCredential() *CredentialTestLogUpdate {
	_u.mutation.ClearCredential()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CredentialTestLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialTestLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CredentialTestLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialTestLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CredentialTestLogUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := credentialtestlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CredentialTestLog.status": %w`, err)}
		}
	}
	if _u.mutation.CredentialCleared() && len(_u.mutation.CredentialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CredentialTestLog.credential"`)
	}
	return nil
}

func (_u *CredentialTestLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credentialtestlog.Table, credentialtestlog.Columns, sqlgraph.NewFieldSpec(credentialtestlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(credentialtestlog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(credentialtestlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(credentialtestlog.FieldErrorMessage, field.TypeString)
	}
	if _u.mutation.CredentialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credentialtestlog.CredentialTable,
			Columns: []string{credentialtestlog.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credentialtestlog.CredentialTable,
			Columns: []string{credentialtestlog.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentialtestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CredentialTestLogUpdateOne is the builder for updating a single CredentialTestLog entity.
type CredentialTestLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CredentialTestLogMutation
}

// SetStatus sets the "status" field.
func (_u *CredentialTestLogUpdateOne) SetStatus(v string) *CredentialTestLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CredentialTestLogUpdateOne) SetNillableStatus(v *string) *CredentialTestLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CredentialTestLogUpdateOne) SetErrorMessage(v string) *CredentialTestLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CredentialTestLogUpdateOne) SetNillableErrorMessage(v *string) *CredentialTestLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CredentialTestLogUpdateOne) ClearErrorMessage() *CredentialTestLogUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCredentialID sets the "credential" edge to the Credential entity by ID.
func (_u *CredentialTestLogUpdateOne) SetCredentialID(id int64) *CredentialTestLogUpdateOne {
	_u.mutation.SetCredentialID(id)
	return _u
}

// SetCredential sets the "credential" edge to the Credential entity.
func (_u *CredentialTestLogUpdateOne) SetCredential(v *Credential) *CredentialTestLogUpdateOne {
	return _u.SetCredentialID(v.ID)
}

// Mutation returns the CredentialTestLogMutation object of the builder.
func (_u *CredentialTestLogUpdateOne) Mutation() *CredentialTestLogMutation {
	return _u.mutation
}

// ClearCredential clears the "credential" edge to the Credential entity.
func (_u *CredentialTestLogUpdateOne) ClearCredential() *CredentialTestLogUpdateOne {
	_u.mutation.ClearCredential()
	return _u
}

// Where appends a list predicates to the CredentialTestLogUpdate builder.
func (_u *CredentialTestLogUpdateOne) Where(ps ...predicate.CredentialTestLog) *CredentialTestLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CredentialTestLogUpdateOne) Select(field string, fields ...string) *CredentialTestLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CredentialTestLog entity.
func (_u *CredentialTestLogUpdateOne) Save(ctx context.Context) (*CredentialTestLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialTestLogUpdateOne) SaveX(ctx context.Context) *CredentialTestLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CredentialTestLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialTestLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CredentialTestLogUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := credentialtestlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CredentialTestLog.status": %w`, err)}
		}
	}
	if _u.mutation.CredentialCleared() && len(_u.mutation.CredentialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CredentialTestLog.credential"`)
	}
	return nil
}

func (_u *CredentialTestLogUpdateOne) sqlSave(ctx context.Context) (_node *CredentialTestLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credentialtestlog.Table, credentialtestlog.Columns, sqlgraph.NewFieldSpec(credentialtestlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CredentialTestLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, credentialtestlog.FieldID)
		for _, f := range fields {
			if !credentialtestlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != credentialtestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(credentialtestlog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(credentialtestlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(credentialtestlog.FieldErrorMessage, field.TypeString)
	}
	if _u.mutation.CredentialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credentialtestlog.CredentialTable,
			Columns: []string{credentialtestlog.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credentialtestlog.CredentialTable,
			Columns: []string{credentialtestlog.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CredentialTestLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentialtestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
