// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/credential"
	"cloudflared-tunnel/ent/predicate"
	"cloudflared-tunnel/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CredentialUpdate is the builder for updating Credential entities.
type CredentialUpdate struct {
	config
	hooks    []Hook
	mutation *CredentialMutation
}

// Where appends a list predicates to the CredentialUpdate builder.
func (_u *CredentialUpdate) Where(ps ...predicate.Credential) *CredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CredentialUpdate) SetName(v string) *CredentialUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CredentialUpdate) SetNillableName(v *string) *CredentialUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIToken sets the "api_token" field.
func (_u *CredentialUpdate) SetAPIToken(v string) *CredentialUpdate {
	_u.mutation.SetAPIToken(v)
	return _u
}

// SetNillableAPIToken sets the "api_token" field if the given value is not nil.
func (_u *CredentialUpdate) SetNillableAPIToken(v *string) *CredentialUpdate {
	if v != nil {
		_u.SetAPIToken(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CredentialUpdate) SetAccountID(v string) *CredentialUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CredentialUpdate) SetNillableAccountID(v *string) *CredentialUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *CredentialUpdate) SetIsDefault(v bool) *CredentialUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *CredentialUpdate) SetNillableIsDefault(v *bool) *CredentialUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialUpdate) SetUpdatedAt(v time.Time) *CredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *CredentialUpdate) SetOwnerID(id int64) *CredentialUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *CredentialUpdate) SetOwner(v *User) *CredentialUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the CredentialMutation object of the builder.
func (_u *CredentialUpdate) Mutation() *CredentialMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *CredentialUpdate) ClearOwner() *CredentialUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := credential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CredentialUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := credential.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Credential.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIToken(); ok {
		if err := credential.APITokenValidator(v); err != nil {
			return &ValidationError{Name: "api_token", err: fmt.Errorf(`ent: validator failed for field "Credential.api_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountID(); ok {
		if err := credential.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "Credential.account_id": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Credential.owner"`)
	}
	return nil
}

func (_u *CredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credential.Table, credential.Columns, sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(credential.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIToken(); ok {
		_spec.SetField(credential.FieldAPIToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(credential.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(credential.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credential.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credential.OwnerTable,
			Columns: []string{credential.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credential.OwnerTable,
			Columns: []string{credential.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CredentialUpdateOne is the builder for updating a single Credential entity.
type CredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CredentialMutation
}

// SetName sets the "name" field.
func (_u *CredentialUpdateOne) SetName(v string) *CredentialUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CredentialUpdateOne) SetNillableName(v *string) *CredentialUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIToken sets the "api_token" field.
func (_u *CredentialUpdateOne) SetAPIToken(v string) *CredentialUpdateOne {
	_u.mutation.SetAPIToken(v)
	return _u
}

// SetNillableAPIToken sets the "api_token" field if the given value is not nil.
func (_u *CredentialUpdateOne) SetNillableAPIToken(v *string) *CredentialUpdateOne {
	if v != nil {
		_u.SetAPIToken(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CredentialUpdateOne) SetAccountID(v string) *CredentialUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CredentialUpdateOne) SetNillableAccountID(v *string) *CredentialUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *CredentialUpdateOne) SetIsDefault(v bool) *CredentialUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *CredentialUpdateOne) SetNillableIsDefault(v *bool) *CredentialUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialUpdateOne) SetUpdatedAt(v time.Time) *CredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *CredentialUpdateOne) SetOwnerID(id int64) *CredentialUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *CredentialUpdateOne) SetOwner(v *User) *CredentialUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the CredentialMutation object of the builder.
func (_u *CredentialUpdateOne) Mutation() *CredentialMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *CredentialUpdateOne) ClearOwner() *CredentialUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the CredentialUpdate builder.
func (_u *CredentialUpdateOne) Where(ps ...predicate.Credential) *CredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CredentialUpdateOne) Select(field string, fields ...string) *CredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Credential entity.
func (_u *CredentialUpdateOne) Save(ctx context.Context) (*Credential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialUpdateOne) SaveX(ctx context.Context) *Credential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := credential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CredentialUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := credential.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Credential.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIToken(); ok {
		if err := credential.APITokenValidator(v); err != nil {
			return &ValidationError{Name: "api_token", err: fmt.Errorf(`ent: validator failed for field "Credential.api_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountID(); ok {
		if err := credential.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "Credential.account_id": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Credential.owner"`)
	}
	return nil
}

func (_u *CredentialUpdateOne) sqlSave(ctx context.Context) (_node *Credential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credential.Table, credential.Columns, sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Credential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, credential.FieldID)
		for _, f := range fields {
			if !credential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != credential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(credential.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIToken(); ok {
		_spec.SetField(credential.FieldAPIToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(credential.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(credential.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credential.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credential.OwnerTable,
			Columns: []string{credential.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credential.OwnerTable,
			Columns: []string{credential.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Credential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
