// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/credential"
	"cloudflared-tunnel/ent/credentialtestlog"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CredentialTestLog is the model entity for the CredentialTestLog schema.
type CredentialTestLog struct {
	config `json:"-"`
	// ID of the ent.
	// 日志ID
	ID int64 `json:"id,omitempty"`
	// 测试结果: success/failed
	Status string `json:"status,omitempty"`
	// 错误信息
	ErrorMessage string `json:"error_message,omitempty"`
	// 测试时间
	TestedAt time.Time `json:"tested_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CredentialTestLogQuery when eager-loading is set.
	Edges                CredentialTestLogEdges `json:"edges"`
	credential_test_logs *int64
	selectValues         sql.SelectValues
}

// CredentialTestLogEdges holds the relations/edges for other nodes in the graph.
type CredentialTestLogEdges struct {
	// 关联凭证
	Credential *Credential `json:"credential,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CredentialOrErr returns the Credential value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CredentialTestLogEdges) CredentialOrErr() (*Credential, error) {
	if e.Credential != nil {
		return e.Credential, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: credential.Label}
	}
	return nil, &NotLoadedError{edge: "credential"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CredentialTestLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case credentialtestlog.FieldID:
			values[i] = new(sql.NullInt64)
		case credentialtestlog.FieldStatus, credentialtestlog.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case credentialtestlog.FieldTestedAt:
			values[i] = new(sql.NullTime)
		case credentialtestlog.ForeignKeys[0]: // credential_test_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CredentialTestLog fields.
func (_m *CredentialTestLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case credentialtestlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case credentialtestlog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case credentialtestlog.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case credentialtestlog.FieldTestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field tested_at", values[i])
			} else if value.Valid {
				_m.TestedAt = value.Time
			}
		case credentialtestlog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field credential_test_logs", value)
			} else if value.Valid {
				_m.credential_test_logs = new(int64)
				*_m.credential_test_logs = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CredentialTestLog.
// This includes values selected through modifiers, order, etc.
func (_m *CredentialTestLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCredential queries the "credential" edge of the CredentialTestLog entity.
func (_m *CredentialTestLog) QueryCredential() *CredentialQuery {
	return NewCredentialTestLogClient(_m.config).QueryCredential(_m)
}

// Update returns a builder for updating this CredentialTestLog.
// Note that you need to call CredentialTestLog.Unwrap() before calling this method if this CredentialTestLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CredentialTestLog) Update() *CredentialTestLogUpdateOne {
	return NewCredentialTestLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CredentialTestLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CredentialTestLog) Unwrap() *CredentialTestLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CredentialTestLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CredentialTestLog) String() string {
	var builder strings.Builder
	builder.WriteString("CredentialTestLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("tested_at=")
	builder.WriteString(_m.TestedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CredentialTestLogs is a parsable slice of CredentialTestLog.
type CredentialTestLogs []*CredentialTestLog
