// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/credential"
	"cloudflared-tunnel/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Credential is the model entity for the Credential schema.
type Credential struct {
	config `json:"-"`
	// ID of the ent.
	// 凭证ID
	ID int64 `json:"id,omitempty"`
	// 凭证名称
	Name string `json:"name,omitempty"`
	// 加密后的 API Token
	APIToken string `json:"api_token,omitempty"`
	// Cloudflare Account ID
	AccountID string `json:"account_id,omitempty"`
	// 是否为默认凭证
	IsDefault bool `json:"is_default,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CredentialQuery when eager-loading is set.
	Edges            CredentialEdges `json:"edges"`
	user_credentials *int64
	selectValues     sql.SelectValues
}

// CredentialEdges holds the relations/edges for other nodes in the graph.
type CredentialEdges struct {
	// 所属用户
	Owner *User `json:"owner,omitempty"`
	// 测试日志
	TestLogs []*CredentialTestLog `json:"test_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CredentialEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// TestLogsOrErr returns the TestLogs value or an error if the edge
// was not loaded in eager-loading.
func (e CredentialEdges) TestLogsOrErr() ([]*CredentialTestLog, error) {
	if e.loadedTypes[1] {
		return e.TestLogs, nil
	}
	return nil, &NotLoadedError{edge: "test_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Credential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case credential.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case credential.FieldID:
			values[i] = new(sql.NullInt64)
		case credential.FieldName, credential.FieldAPIToken, credential.FieldAccountID:
			values[i] = new(sql.NullString)
		case credential.FieldCreatedAt, credential.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case credential.ForeignKeys[0]: // user_credentials
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Credential fields.
func (_m *Credential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case credential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case credential.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case credential.FieldAPIToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_token", values[i])
			} else if value.Valid {
				_m.APIToken = value.String
			}
		case credential.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case credential.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		case credential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case credential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case credential.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_credentials", value)
			} else if value.Valid {
				_m.user_credentials = new(int64)
				*_m.user_credentials = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Credential.
// This includes values selected through modifiers, order, etc.
func (_m *Credential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Credential entity.
func (_m *Credential) QueryOwner() *UserQuery {
	return NewCredentialClient(_m.config).QueryOwner(_m)
}

// QueryTestLogs queries the "test_logs" edge of the Credential entity.
func (_m *Credential) QueryTestLogs() *CredentialTestLogQuery {
	return NewCredentialClient(_m.config).QueryTestLogs(_m)
}

// Update returns a builder for updating this Credential.
// Note that you need to call Credential.Unwrap() before calling this method if this Credential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Credential) Update() *CredentialUpdateOne {
	return NewCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Credential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Credential) Unwrap() *Credential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Credential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Credential) String() string {
	var builder strings.Builder
	builder.WriteString("Credential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("api_token=")
	builder.WriteString(_m.APIToken)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Credentials is a parsable slice of Credential.
type Credentials []*Credential
