// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/credential"
	"cloudflared-tunnel/ent/credentialtestlog"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CredentialTestLogCreate is the builder for creating a CredentialTestLog entity.
type CredentialTestLogCreate struct {
	config
	mutation *CredentialTestLogMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *CredentialTestLogCreate) SetStatus(v string) *CredentialTestLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *CredentialTestLogCreate) SetErrorMessage(v string) *CredentialTestLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *CredentialTestLogCreate) SetNillableErrorMessage(v *string) *CredentialTestLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetTestedAt sets the "tested_at" field.
func (_c *CredentialTestLogCreate) SetTestedAt(v time.Time) *CredentialTestLogCreate {
	_c.mutation.SetTestedAt(v)
	return _c
}

// SetNillableTestedAt sets the "tested_at" field if the given value is not nil.
func (_c *CredentialTestLogCreate) SetNillableTestedAt(v *time.Time) *CredentialTestLogCreate {
	if v != nil {
		_c.SetTestedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CredentialTestLogCreate) SetID(v int64) *CredentialTestLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCredentialID sets the "credential" edge to the Credential entity by ID.
func (_c *CredentialTestLogCreate) SetCredentialID(id int64) *CredentialTestLogCreate {
	_c.mutation.SetCredentialID(id)
	return _c
}

// SetCredential sets the "credential" edge to the Credential entity.
func (_c *CredentialTestLogCreate) SetCredential(v *Credential) *CredentialTestLogCreate {
	return _c.SetCredentialID(v.ID)
}

// Mutation returns the CredentialTestLogMutation object of the builder.
func (_c *CredentialTestLogCreate) Mutation() *CredentialTestLogMutation {
	return _c.mutation
}

// Save creates the CredentialTestLog in the database.
func (_c *CredentialTestLogCreate) Save(ctx context.Context) (*CredentialTestLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CredentialTestLogCreate) SaveX(ctx context.Context) *CredentialTestLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CredentialTestLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CredentialTestLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CredentialTestLogCreate) defaults() {
	if _, ok := _c.mutation.TestedAt(); !ok {
		v := credentialtestlog.DefaultTestedAt()
		_c.mutation.SetTestedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CredentialTestLogCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CredentialTestLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := credentialtestlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CredentialTestLog.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TestedAt(); !ok {
		return &ValidationError{Name: "tested_at", err: errors.New(`ent: missing required field "CredentialTestLog.tested_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := credentialtestlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CredentialTestLog.id": %w`, err)}
		}
	}
	if len(_c.mutation.CredentialIDs()) == 0 {
		return &ValidationError{Name: "credential", err: errors.New(`ent: missing required edge "CredentialTestLog.credential"`)}
	}
	return nil
}

func (_c *CredentialTestLogCreate) sqlSave(ctx context.Context) (*CredentialTestLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CredentialTestLogCreate) createSpec() (*CredentialTestLog, *sqlgraph.CreateSpec) {
	var (
		_node = &CredentialTestLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(credentialtestlog.Table, sqlgraph.NewFieldSpec(credentialtestlog.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(credentialtestlog.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(credentialtestlog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.TestedAt(); ok {
		_spec.SetField(credentialtestlog.FieldTestedAt, field.TypeTime, value)
		_node.TestedAt = value
	}
	if nodes := _c.mutation.CredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credentialtestlog.CredentialTable,
			Columns: []string{credentialtestlog.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.credential_test_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CredentialTestLogCreateBulk is the builder for creating many CredentialTestLog entities in bulk.
type CredentialTestLogCreateBulk struct {
	config
	err      error
	builders []*CredentialTestLogCreate
}

// Save creates the CredentialTestLog entities in the database.
func (_c *CredentialTestLogCreateBulk) Save(ctx context.Context) ([]*CredentialTestLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CredentialTestLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CredentialTestLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CredentialTestLogCreateBulk) SaveX(ctx context.Context) []*CredentialTestLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CredentialTestLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CredentialTestLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
