// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/credentialtestlog"
	"cloudflared-tunnel/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CredentialTestLogDelete is the builder for deleting a CredentialTestLog entity.
type CredentialTestLogDelete struct {
	config
	hooks    []Hook
	mutation *CredentialTestLogMutation
}

// Where appends a list predicates to the CredentialTestLogDelete builder.
func (_d *CredentialTestLogDelete) Where(ps ...predicate.CredentialTestLog) *CredentialTestLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CredentialTestLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CredentialTestLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CredentialTestLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(credentialtestlog.Table, sqlgraph.NewFieldSpec(credentialtestlog.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CredentialTestLogDeleteOne is the builder for deleting a single CredentialTestLog entity.
type CredentialTestLogDeleteOne struct {
	_d *CredentialTestLogDelete
}

// Where appends a list predicates to the CredentialTestLogDelete builder.
func (_d *CredentialTestLogDeleteOne) Where(ps ...predicate.CredentialTestLog) *CredentialTestLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CredentialTestLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{credentialtestlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CredentialTestLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
