// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/credential"
	"cloudflared-tunnel/ent/credentialtestlog"
	"cloudflared-tunnel/ent/predicate"
	"cloudflared-tunnel/ent/tunneltrafficlog"
	"cloudflared-tunnel/ent/user"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCredential        = "Credential"
	TypeCredentialTestLog = "CredentialTestLog"
	TypeTunnelTrafficLog  = "TunnelTrafficLog"
	TypeUser              = "User"
)

// CredentialMutation represents an operation that mutates the Credential nodes in the graph.
type CredentialMutation struct {
	config
	op               Op
	typ              string
	id               *int64
	name             *string
	api_token        *string
	account_id       *string
	is_default       *bool
	created_at       *time.Time
	updated_at       *time.Time
	clearedFields    map[string]struct{}
	owner            *int64
	clearedowner     bool
	test_logs        map[int64]struct{}
	removedtest_logs map[int64]struct{}
	clearedtest_logs bool
	done             bool
	oldValue         func(context.Context) (*Credential, error)
	predicates       []predicate.Credential
}

var _ ent.Mutation = (*CredentialMutation)(nil)

// credentialOption allows management of the mutation configuration using functional options.
type credentialOption func(*CredentialMutation)

// newCredentialMutation creates new mutation for the Credential entity.
func newCredentialMutation(c config, op Op, opts ...credentialOption) *CredentialMutation {
	m := &CredentialMutation{
		config:        c,
		op:            op,
		typ:           TypeCredential,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCredentialID sets the ID field of the mutation.
func withCredentialID(id int64) credentialOption {
	return func(m *CredentialMutation) {
		var (
			err   error
			once  sync.Once
			value *Credential
		)
		m.oldValue = func(ctx context.Context) (*Credential, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Credential.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCredential sets the old Credential of the mutation.
func withCredential(node *Credential) credentialOption {
	return func(m *CredentialMutation) {
		m.oldValue = func(context.Context) (*Credential, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CredentialMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CredentialMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Credential entities.
func (m *CredentialMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CredentialMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CredentialMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Credential.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *CredentialMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *CredentialMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Credential entity.
// If the Credential object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CredentialMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *CredentialMutation) ResetName() {
	m.name = nil
}

// SetAPIToken sets the "api_token" field.
func (m *CredentialMutation) SetAPIToken(s string) {
	m.api_token = &s
}

// APIToken returns the value of the "api_token" field in the mutation.
func (m *CredentialMutation) APIToken() (r string, exists bool) {
	v := m.api_token
	if v == nil {
		return
	}
	return *v, true
}

// OldAPIToken returns the old "api_token" field's value of the Credential entity.
// If the Credential object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CredentialMutation) OldAPIToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAPIToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAPIToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAPIToken: %w", err)
	}
	return oldValue.APIToken, nil
}

// ResetAPIToken resets all changes to the "api_token" field.
func (m *CredentialMutation) ResetAPIToken() {
	m.api_token = nil
}

// SetAccountID sets the "account_id" field.
func (m *CredentialMutation) SetAccountID(s string) {
	m.account_id = &s
}

// AccountID returns the value of the "account_id" field in the mutation.
func (m *CredentialMutation) AccountID() (r string, exists bool) {
	v := m.account_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountID returns the old "account_id" field's value of the Credential entity.
// If the Credential object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CredentialMutation) OldAccountID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountID: %w", err)
	}
	return oldValue.AccountID, nil
}

// ResetAccountID resets all changes to the "account_id" field.
func (m *CredentialMutation) ResetAccountID() {
	m.account_id = nil
}

// SetIsDefault sets the "is_default" field.
func (m *CredentialMutation) SetIsDefault(b bool) {
	m.is_default = &b
}

// IsDefault returns the value of the "is_default" field in the mutation.
func (m *CredentialMutation) IsDefault() (r bool, exists bool) {
	v := m.is_default
	if v == nil {
		return
	}
	return *v, true
}

// OldIsDefault returns the old "is_default" field's value of the Credential entity.
// If the Credential object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CredentialMutation) OldIsDefault(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsDefault is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsDefault requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsDefault: %w", err)
	}
	return oldValue.IsDefault, nil
}

// ResetIsDefault resets all changes to the "is_default" field.
func (m *CredentialMutation) ResetIsDefault() {
	m.is_default = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *CredentialMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *CredentialMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Credential entity.
// If the Credential object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CredentialMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *CredentialMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *CredentialMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *CredentialMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Credential entity.
// If the Credential object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CredentialMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *CredentialMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetOwnerID sets the "owner" edge to the User entity by id.
func (m *CredentialMutation) SetOwnerID(id int64) {
	m.owner = &id
}

// ClearOwner clears the "owner" edge to the User entity.
func (m *CredentialMutation) ClearOwner() {
	m.clearedowner = true
}

// OwnerCleared reports if the "owner" edge to the User entity was cleared.
func (m *CredentialMutation) OwnerCleared() bool {
	return m.clearedowner
}

// OwnerID returns the "owner" edge ID in the mutation.
func (m *CredentialMutation) OwnerID() (id int64, exists bool) {
	if m.owner != nil {
		return *m.owner, true
	}
	return
}

// OwnerIDs returns the "owner" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// OwnerID instead. It exists only for internal usage by the builders.
func (m *CredentialMutation) OwnerIDs() (ids []int64) {
	if id := m.owner; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetOwner resets all changes to the "owner" edge.
func (m *CredentialMutation) ResetOwner() {
	m.owner = nil
	m.clearedowner = false
}

// AddTestLogIDs adds the "test_logs" edge to the CredentialTestLog entity by ids.
func (m *CredentialMutation) AddTestLogIDs(ids ...int64) {
	if m.test_logs == nil {
		m.test_logs = make(map[int64]struct{})
	}
	for i := range ids {
		m.test_logs[ids[i]] = struct{}{}
	}
}

// ClearTestLogs clears the "test_logs" edge to the CredentialTestLog entity.
func (m *CredentialMutation) ClearTestLogs() {
	m.clearedtest_logs = true
}

// TestLogsCleared reports if the "test_logs" edge to the CredentialTestLog entity was cleared.
func (m *CredentialMutation) TestLogsCleared() bool {
	return m.clearedtest_logs
}

// RemoveTestLogIDs removes the "test_logs" edge to the CredentialTestLog entity by IDs.
func (m *CredentialMutation) RemoveTestLogIDs(ids ...int64) {
	if m.removedtest_logs == nil {
		m.removedtest_logs = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.test_logs, ids[i])
		m.removedtest_logs[ids[i]] = struct{}{}
	}
}

// RemovedTestLogs returns the removed IDs of the "test_logs" edge to the CredentialTestLog entity.
func (m *CredentialMutation) RemovedTestLogsIDs() (ids []int64) {
	for id := range m.removedtest_logs {
		ids = append(ids, id)
	}
	return
}

// TestLogsIDs returns the "test_logs" edge IDs in the mutation.
func (m *CredentialMutation) TestLogsIDs() (ids []int64) {
	for id := range m.test_logs {
		ids = append(ids, id)
	}
	return
}

// ResetTestLogs resets all changes to the "test_logs" edge.
func (m *CredentialMutation) ResetTestLogs() {
	m.test_logs = nil
	m.clearedtest_logs = false
	m.removedtest_logs = nil
}

// Where appends a list predicates to the CredentialMutation builder.
func (m *CredentialMutation) Where(ps ...predicate.Credential) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CredentialMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CredentialMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Credential, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CredentialMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CredentialMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Credential).
func (m *CredentialMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CredentialMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.name != nil {
		fields = append(fields, credential.FieldName)
	}
	if m.api_token != nil {
		fields = append(fields, credential.FieldAPIToken)
	}
	if m.account_id != nil {
		fields = append(fields, credential.FieldAccountID)
	}
	if m.is_default != nil {
		fields = append(fields, credential.FieldIsDefault)
	}
	if m.created_at != nil {
		fields = append(fields, credential.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, credential.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CredentialMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case credential.FieldName:
		return m.Name()
	case credential.FieldAPIToken:
		return m.APIToken()
	case credential.FieldAccountID:
		return m.AccountID()
	case credential.FieldIsDefault:
		return m.IsDefault()
	case credential.FieldCreatedAt:
		return m.CreatedAt()
	case credential.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CredentialMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case credential.FieldName:
		return m.OldName(ctx)
	case credential.FieldAPIToken:
		return m.OldAPIToken(ctx)
	case credential.FieldAccountID:
		return m.OldAccountID(ctx)
	case credential.FieldIsDefault:
		return m.OldIsDefault(ctx)
	case credential.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case credential.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Credential field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CredentialMutation) SetField(name string, value ent.Value) error {
	switch name {
	case credential.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case credential.FieldAPIToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAPIToken(v)
		return nil
	case credential.FieldAccountID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountID(v)
		return nil
	case credential.FieldIsDefault:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsDefault(v)
		return nil
	case credential.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case credential.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Credential field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CredentialMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CredentialMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CredentialMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Credential numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CredentialMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CredentialMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CredentialMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Credential nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CredentialMutation) ResetField(name string) error {
	switch name {
	case credential.FieldName:
		m.ResetName()
		return nil
	case credential.FieldAPIToken:
		m.ResetAPIToken()
		return nil
	case credential.FieldAccountID:
		m.ResetAccountID()
		return nil
	case credential.FieldIsDefault:
		m.ResetIsDefault()
		return nil
	case credential.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case credential.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Credential field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CredentialMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.owner != nil {
		edges = append(edges, credential.EdgeOwner)
	}
	if m.test_logs != nil {
		edges = append(edges, credential.EdgeTestLogs)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CredentialMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case credential.EdgeOwner:
		if id := m.owner; id != nil {
			return []ent.Value{*id}
		}
	case credential.EdgeTestLogs:
		ids := make([]ent.Value, 0, len(m.test_logs))
		for id := range m.test_logs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CredentialMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedtest_logs != nil {
		edges = append(edges, credential.EdgeTestLogs)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CredentialMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case credential.EdgeTestLogs:
		ids := make([]ent.Value, 0, len(m.removedtest_logs))
		for id := range m.removedtest_logs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CredentialMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedowner {
		edges = append(edges, credential.EdgeOwner)
	}
	if m.clearedtest_logs {
		edges = append(edges, credential.EdgeTestLogs)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CredentialMutation) EdgeCleared(name string) bool {
	switch name {
	case credential.EdgeOwner:
		return m.clearedowner
	case credential.EdgeTestLogs:
		return m.clearedtest_logs
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CredentialMutation) ClearEdge(name string) error {
	switch name {
	case credential.EdgeOwner:
		m.ClearOwner()
		return nil
	}
	return fmt.Errorf("unknown Credential unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CredentialMutation) ResetEdge(name string) error {
	switch name {
	case credential.EdgeOwner:
		m.ResetOwner()
		return nil
	case credential.EdgeTestLogs:
		m.ResetTestLogs()
		return nil
	}
	return fmt.Errorf("unknown Credential edge %s", name)
}

// CredentialTestLogMutation represents an operation that mutates the CredentialTestLog nodes in the graph.
type CredentialTestLogMutation struct {
	config
	op                Op
	typ               string
	id                *int64
	status            *string
	error_message     *string
	tested_at         *time.Time
	clearedFields     map[string]struct{}
	credential        *int64
	clearedcredential bool
	done              bool
	oldValue          func(context.Context) (*CredentialTestLog, error)
	predicates        []predicate.CredentialTestLog
}

var _ ent.Mutation = (*CredentialTestLogMutation)(nil)

// credentialtestlogOption allows management of the mutation configuration using functional options.
type credentialtestlogOption func(*CredentialTestLogMutation)

// newCredentialTestLogMutation creates new mutation for the CredentialTestLog entity.
func newCredentialTestLogMutation(c config, op Op, opts ...credentialtestlogOption) *CredentialTestLogMutation {
	m := &CredentialTestLogMutation{
		config:        c,
		op:            op,
		typ:           TypeCredentialTestLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCredentialTestLogID sets the ID field of the mutation.
func withCredentialTestLogID(id int64) credentialtestlogOption {
	return func(m *CredentialTestLogMutation) {
		var (
			err   error
			once  sync.Once
			value *CredentialTestLog
		)
		m.oldValue = func(ctx context.Context) (*CredentialTestLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().CredentialTestLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCredentialTestLog sets the old CredentialTestLog of the mutation.
func withCredentialTestLog(node *CredentialTestLog) credentialtestlogOption {
	return func(m *CredentialTestLogMutation) {
		m.oldValue = func(context.Context) (*CredentialTestLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CredentialTestLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CredentialTestLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of CredentialTestLog entities.
func (m *CredentialTestLogMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CredentialTestLogMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CredentialTestLogMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().CredentialTestLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetStatus sets the "status" field.
func (m *CredentialTestLogMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *CredentialTestLogMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the CredentialTestLog entity.
// If the CredentialTestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CredentialTestLogMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *CredentialTestLogMutation) ResetStatus() {
	m.status = nil
}

// SetErrorMessage sets the "error_message" field.
func (m *CredentialTestLogMutation) SetErrorMessage(s string) {
	m.error_message = &s
}

// ErrorMessage returns the value of the "error_message" field in the mutation.
func (m *CredentialTestLogMutation) ErrorMessage() (r string, exists bool) {
	v := m.error_message
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorMessage returns the old "error_message" field's value of the CredentialTestLog entity.
// If the CredentialTestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CredentialTestLogMutation) OldErrorMessage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorMessage: %w", err)
	}
	return oldValue.ErrorMessage, nil
}

// ClearErrorMessage clears the value of the "error_message" field.
func (m *CredentialTestLogMutation) ClearErrorMessage() {
	m.error_message = nil
	m.clearedFields[credentialtestlog.FieldErrorMessage] = struct{}{}
}

// ErrorMessageCleared returns if the "error_message" field was cleared in this mutation.
func (m *CredentialTestLogMutation) ErrorMessageCleared() bool {
	_, ok := m.clearedFields[credentialtestlog.FieldErrorMessage]
	return ok
}

// ResetErrorMessage resets all changes to the "error_message" field.
func (m *CredentialTestLogMutation) ResetErrorMessage() {
	m.error_message = nil
	delete(m.clearedFields, credentialtestlog.FieldErrorMessage)
}

// SetTestedAt sets the "tested_at" field.
func (m *CredentialTestLogMutation) SetTestedAt(t time.Time) {
	m.tested_at = &t
}

// TestedAt returns the value of the "tested_at" field in the mutation.
func (m *CredentialTestLogMutation) TestedAt() (r time.Time, exists bool) {
	v := m.tested_at
	if v == nil {
		return
	}
	return *v, true
}

// OldTestedAt returns the old "tested_at" field's value of the CredentialTestLog entity.
// If the CredentialTestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CredentialTestLogMutation) OldTestedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTestedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTestedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTestedAt: %w", err)
	}
	return oldValue.TestedAt, nil
}

// ResetTestedAt resets all changes to the "tested_at" field.
func (m *CredentialTestLogMutation) ResetTestedAt() {
	m.tested_at = nil
}

// SetCredentialID sets the "credential" edge to the Credential entity by id.
func (m *CredentialTestLogMutation) SetCredentialID(id int64) {
	m.credential = &id
}

// ClearCredential clears the "credential" edge to the Credential entity.
func (m *CredentialTestLogMutation) ClearCredential() {
	m.clearedcredential = true
}

// CredentialCleared reports if the "credential" edge to the Credential entity was cleared.
func (m *CredentialTestLogMutation) CredentialCleared() bool {
	return m.clearedcredential
}

// CredentialID returns the "credential" edge ID in the mutation.
func (m *CredentialTestLogMutation) CredentialID() (id int64, exists bool) {
	if m.credential != nil {
		return *m.credential, true
	}
	return
}

// CredentialIDs returns the "credential" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// CredentialID instead. It exists only for internal usage by the builders.
func (m *CredentialTestLogMutation) CredentialIDs() (ids []int64) {
	if id := m.credential; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetCredential resets all changes to the "credential" edge.
func (m *CredentialTestLogMutation) ResetCredential() {
	m.credential = nil
	m.clearedcredential = false
}

// Where appends a list predicates to the CredentialTestLogMutation builder.
func (m *CredentialTestLogMutation) Where(ps ...predicate.CredentialTestLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CredentialTestLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CredentialTestLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.CredentialTestLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CredentialTestLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CredentialTestLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (CredentialTestLog).
func (m *CredentialTestLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CredentialTestLogMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.status != nil {
		fields = append(fields, credentialtestlog.FieldStatus)
	}
	if m.error_message != nil {
		fields = append(fields, credentialtestlog.FieldErrorMessage)
	}
	if m.tested_at != nil {
		fields = append(fields, credentialtestlog.FieldTestedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CredentialTestLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case credentialtestlog.FieldStatus:
		return m.Status()
	case credentialtestlog.FieldErrorMessage:
		return m.ErrorMessage()
	case credentialtestlog.FieldTestedAt:
		return m.TestedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CredentialTestLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case credentialtestlog.FieldStatus:
		return m.OldStatus(ctx)
	case credentialtestlog.FieldErrorMessage:
		return m.OldErrorMessage(ctx)
	case credentialtestlog.FieldTestedAt:
		return m.OldTestedAt(ctx)
	}
	return nil, fmt.Errorf("unknown CredentialTestLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CredentialTestLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case credentialtestlog.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case credentialtestlog.FieldErrorMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorMessage(v)
		return nil
	case credentialtestlog.FieldTestedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTestedAt(v)
		return nil
	}
	return fmt.Errorf("unknown CredentialTestLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CredentialTestLogMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CredentialTestLogMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CredentialTestLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown CredentialTestLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CredentialTestLogMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(credentialtestlog.FieldErrorMessage) {
		fields = append(fields, credentialtestlog.FieldErrorMessage)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CredentialTestLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CredentialTestLogMutation) ClearField(name string) error {
	switch name {
	case credentialtestlog.FieldErrorMessage:
		m.ClearErrorMessage()
		return nil
	}
	return fmt.Errorf("unknown CredentialTestLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CredentialTestLogMutation) ResetField(name string) error {
	switch name {
	case credentialtestlog.FieldStatus:
		m.ResetStatus()
		return nil
	case credentialtestlog.FieldErrorMessage:
		m.ResetErrorMessage()
		return nil
	case credentialtestlog.FieldTestedAt:
		m.ResetTestedAt()
		return nil
	}
	return fmt.Errorf("unknown CredentialTestLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CredentialTestLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.credential != nil {
		edges = append(edges, credentialtestlog.EdgeCredential)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CredentialTestLogMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case credentialtestlog.EdgeCredential:
		if id := m.credential; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CredentialTestLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CredentialTestLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CredentialTestLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedcredential {
		edges = append(edges, credentialtestlog.EdgeCredential)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CredentialTestLogMutation) EdgeCleared(name string) bool {
	switch name {
	case credentialtestlog.EdgeCredential:
		return m.clearedcredential
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CredentialTestLogMutation) ClearEdge(name string) error {
	switch name {
	case credentialtestlog.EdgeCredential:
		m.ClearCredential()
		return nil
	}
	return fmt.Errorf("unknown CredentialTestLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CredentialTestLogMutation) ResetEdge(name string) error {
	switch name {
	case credentialtestlog.EdgeCredential:
		m.ResetCredential()
		return nil
	}
	return fmt.Errorf("unknown CredentialTestLog edge %s", name)
}

// TunnelTrafficLogMutation represents an operation that mutates the TunnelTrafficLog nodes in the graph.
type TunnelTrafficLogMutation struct {
	config
	op                Op
	typ               string
	id                *int64
	tunnel_id         *string
	bytes_in          *int64
	addbytes_in       *int64
	bytes_out         *int64
	addbytes_out      *int64
	total_requests    *int64
	addtotal_requests *int64
	recorded_at       *time.Time
	clearedFields     map[string]struct{}
	user              *int64
	cleareduser       bool
	done              bool
	oldValue          func(context.Context) (*TunnelTrafficLog, error)
	predicates        []predicate.TunnelTrafficLog
}

var _ ent.Mutation = (*TunnelTrafficLogMutation)(nil)

// tunneltrafficlogOption allows management of the mutation configuration using functional options.
type tunneltrafficlogOption func(*TunnelTrafficLogMutation)

// newTunnelTrafficLogMutation creates new mutation for the TunnelTrafficLog entity.
func newTunnelTrafficLogMutation(c config, op Op, opts ...tunneltrafficlogOption) *TunnelTrafficLogMutation {
	m := &TunnelTrafficLogMutation{
		config:        c,
		op:            op,
		typ:           TypeTunnelTrafficLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTunnelTrafficLogID sets the ID field of the mutation.
func withTunnelTrafficLogID(id int64) tunneltrafficlogOption {
	return func(m *TunnelTrafficLogMutation) {
		var (
			err   error
			once  sync.Once
			value *TunnelTrafficLog
		)
		m.oldValue = func(ctx context.Context) (*TunnelTrafficLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TunnelTrafficLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTunnelTrafficLog sets the old TunnelTrafficLog of the mutation.
func withTunnelTrafficLog(node *TunnelTrafficLog) tunneltrafficlogOption {
	return func(m *TunnelTrafficLogMutation) {
		m.oldValue = func(context.Context) (*TunnelTrafficLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TunnelTrafficLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TunnelTrafficLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of TunnelTrafficLog entities.
func (m *TunnelTrafficLogMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TunnelTrafficLogMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TunnelTrafficLogMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TunnelTrafficLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTunnelID sets the "tunnel_id" field.
func (m *TunnelTrafficLogMutation) SetTunnelID(s string) {
	m.tunnel_id = &s
}

// TunnelID returns the value of the "tunnel_id" field in the mutation.
func (m *TunnelTrafficLogMutation) TunnelID() (r string, exists bool) {
	v := m.tunnel_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTunnelID returns the old "tunnel_id" field's value of the TunnelTrafficLog entity.
// If the TunnelTrafficLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelTrafficLogMutation) OldTunnelID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTunnelID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTunnelID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTunnelID: %w", err)
	}
	return oldValue.TunnelID, nil
}

// ResetTunnelID resets all changes to the "tunnel_id" field.
func (m *TunnelTrafficLogMutation) ResetTunnelID() {
	m.tunnel_id = nil
}

// SetBytesIn sets the "bytes_in" field.
func (m *TunnelTrafficLogMutation) SetBytesIn(i int64) {
	m.bytes_in = &i
	m.addbytes_in = nil
}

// BytesIn returns the value of the "bytes_in" field in the mutation.
func (m *TunnelTrafficLogMutation) BytesIn() (r int64, exists bool) {
	v := m.bytes_in
	if v == nil {
		return
	}
	return *v, true
}

// OldBytesIn returns the old "bytes_in" field's value of the TunnelTrafficLog entity.
// If the TunnelTrafficLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelTrafficLogMutation) OldBytesIn(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBytesIn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBytesIn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBytesIn: %w", err)
	}
	return oldValue.BytesIn, nil
}

// AddBytesIn adds i to the "bytes_in" field.
func (m *TunnelTrafficLogMutation) AddBytesIn(i int64) {
	if m.addbytes_in != nil {
		*m.addbytes_in += i
	} else {
		m.addbytes_in = &i
	}
}

// AddedBytesIn returns the value that was added to the "bytes_in" field in this mutation.
func (m *TunnelTrafficLogMutation) AddedBytesIn() (r int64, exists bool) {
	v := m.addbytes_in
	if v == nil {
		return
	}
	return *v, true
}

// ResetBytesIn resets all changes to the "bytes_in" field.
func (m *TunnelTrafficLogMutation) ResetBytesIn() {
	m.bytes_in = nil
	m.addbytes_in = nil
}

// SetBytesOut sets the "bytes_out" field.
func (m *TunnelTrafficLogMutation) SetBytesOut(i int64) {
	m.bytes_out = &i
	m.addbytes_out = nil
}

// BytesOut returns the value of the "bytes_out" field in the mutation.
func (m *TunnelTrafficLogMutation) BytesOut() (r int64, exists bool) {
	v := m.bytes_out
	if v == nil {
		return
	}
	return *v, true
}

// OldBytesOut returns the old "bytes_out" field's value of the TunnelTrafficLog entity.
// If the TunnelTrafficLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelTrafficLogMutation) OldBytesOut(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBytesOut is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBytesOut requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBytesOut: %w", err)
	}
	return oldValue.BytesOut, nil
}

// AddBytesOut adds i to the "bytes_out" field.
func (m *TunnelTrafficLogMutation) AddBytesOut(i int64) {
	if m.addbytes_out != nil {
		*m.addbytes_out += i
	} else {
		m.addbytes_out = &i
	}
}

// AddedBytesOut returns the value that was added to the "bytes_out" field in this mutation.
func (m *TunnelTrafficLogMutation) AddedBytesOut() (r int64, exists bool) {
	v := m.addbytes_out
	if v == nil {
		return
	}
	return *v, true
}

// ResetBytesOut resets all changes to the "bytes_out" field.
func (m *TunnelTrafficLogMutation) ResetBytesOut() {
	m.bytes_out = nil
	m.addbytes_out = nil
}

// SetTotalRequests sets the "total_requests" field.
func (m *TunnelTrafficLogMutation) SetTotalRequests(i int64) {
	m.total_requests = &i
	m.addtotal_requests = nil
}

// TotalRequests returns the value of the "total_requests" field in the mutation.
func (m *TunnelTrafficLogMutation) TotalRequests() (r int64, exists bool) {
	v := m.total_requests
	if v == nil {
		return
	}
	return *v, true
}

// OldTotalRequests returns the old "total_requests" field's value of the TunnelTrafficLog entity.
// If the TunnelTrafficLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelTrafficLogMutation) OldTotalRequests(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTotalRequests is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTotalRequests requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTotalRequests: %w", err)
	}
	return oldValue.TotalRequests, nil
}

// AddTotalRequests adds i to the "total_requests" field.
func (m *TunnelTrafficLogMutation) AddTotalRequests(i int64) {
	if m.addtotal_requests != nil {
		*m.addtotal_requests += i
	} else {
		m.addtotal_requests = &i
	}
}

// AddedTotalRequests returns the value that was added to the "total_requests" field in this mutation.
func (m *TunnelTrafficLogMutation) AddedTotalRequests() (r int64, exists bool) {
	v := m.addtotal_requests
	if v == nil {
		return
	}
	return *v, true
}

// ResetTotalRequests resets all changes to the "total_requests" field.
func (m *TunnelTrafficLogMutation) ResetTotalRequests() {
	m.total_requests = nil
	m.addtotal_requests = nil
}

// SetRecordedAt sets the "recorded_at" field.
func (m *TunnelTrafficLogMutation) SetRecordedAt(t time.Time) {
	m.recorded_at = &t
}

// RecordedAt returns the value of the "recorded_at" field in the mutation.
func (m *TunnelTrafficLogMutation) RecordedAt() (r time.Time, exists bool) {
	v := m.recorded_at
	if v == nil {
		return
	}
	return *v, true
}

// OldRecordedAt returns the old "recorded_at" field's value of the TunnelTrafficLog entity.
// If the TunnelTrafficLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelTrafficLogMutation) OldRecordedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRecordedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRecordedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRecordedAt: %w", err)
	}
	return oldValue.RecordedAt, nil
}

// ResetRecordedAt resets all changes to the "recorded_at" field.
func (m *TunnelTrafficLogMutation) ResetRecordedAt() {
	m.recorded_at = nil
}

// SetUserID sets the "user" edge to the User entity by id.
func (m *TunnelTrafficLogMutation) SetUserID(id int64) {
	m.user = &id
}

// ClearUser clears the "user" edge to the User entity.
func (m *TunnelTrafficLogMutation) ClearUser() {
	m.cleareduser = true
}

// UserCleared reports if the "user" edge to the User entity was cleared.
func (m *TunnelTrafficLogMutation) UserCleared() bool {
	return m.cleareduser
}

// UserID returns the "user" edge ID in the mutation.
func (m *TunnelTrafficLogMutation) UserID() (id int64, exists bool) {
	if m.user != nil {
		return *m.user, true
	}
	return
}

// UserIDs returns the "user" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// UserID instead. It exists only for internal usage by the builders.
func (m *TunnelTrafficLogMutation) UserIDs() (ids []int64) {
	if id := m.user; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetUser resets all changes to the "user" edge.
func (m *TunnelTrafficLogMutation) ResetUser() {
	m.user = nil
	m.cleareduser = false
}

// Where appends a list predicates to the TunnelTrafficLogMutation builder.
func (m *TunnelTrafficLogMutation) Where(ps ...predicate.TunnelTrafficLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TunnelTrafficLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TunnelTrafficLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TunnelTrafficLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TunnelTrafficLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TunnelTrafficLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TunnelTrafficLog).
func (m *TunnelTrafficLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TunnelTrafficLogMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.tunnel_id != nil {
		fields = append(fields, tunneltrafficlog.FieldTunnelID)
	}
	if m.bytes_in != nil {
		fields = append(fields, tunneltrafficlog.FieldBytesIn)
	}
	if m.bytes_out != nil {
		fields = append(fields, tunneltrafficlog.FieldBytesOut)
	}
	if m.total_requests != nil {
		fields = append(fields, tunneltrafficlog.FieldTotalRequests)
	}
	if m.recorded_at != nil {
		fields = append(fields, tunneltrafficlog.FieldRecordedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TunnelTrafficLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tunneltrafficlog.FieldTunnelID:
		return m.TunnelID()
	case tunneltrafficlog.FieldBytesIn:
		return m.BytesIn()
	case tunneltrafficlog.FieldBytesOut:
		return m.BytesOut()
	case tunneltrafficlog.FieldTotalRequests:
		return m.TotalRequests()
	case tunneltrafficlog.FieldRecordedAt:
		return m.RecordedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TunnelTrafficLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tunneltrafficlog.FieldTunnelID:
		return m.OldTunnelID(ctx)
	case tunneltrafficlog.FieldBytesIn:
		return m.OldBytesIn(ctx)
	case tunneltrafficlog.FieldBytesOut:
		return m.OldBytesOut(ctx)
	case tunneltrafficlog.FieldTotalRequests:
		return m.OldTotalRequests(ctx)
	case tunneltrafficlog.FieldRecordedAt:
		return m.OldRecordedAt(ctx)
	}
	return nil, fmt.Errorf("unknown TunnelTrafficLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TunnelTrafficLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tunneltrafficlog.FieldTunnelID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTunnelID(v)
		return nil
	case tunneltrafficlog.FieldBytesIn:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBytesIn(v)
		return nil
	case tunneltrafficlog.FieldBytesOut:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBytesOut(v)
		return nil
	case tunneltrafficlog.FieldTotalRequests:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTotalRequests(v)
		return nil
	case tunneltrafficlog.FieldRecordedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRecordedAt(v)
		return nil
	}
	return fmt.Errorf("unknown TunnelTrafficLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TunnelTrafficLogMutation) AddedFields() []string {
	var fields []string
	if m.addbytes_in != nil {
		fields = append(fields, tunneltrafficlog.FieldBytesIn)
	}
	if m.addbytes_out != nil {
		fields = append(fields, tunneltrafficlog.FieldBytesOut)
	}
	if m.addtotal_requests != nil {
		fields = append(fields, tunneltrafficlog.FieldTotalRequests)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TunnelTrafficLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case tunneltrafficlog.FieldBytesIn:
		return m.AddedBytesIn()
	case tunneltrafficlog.FieldBytesOut:
		return m.AddedBytesOut()
	case tunneltrafficlog.FieldTotalRequests:
		return m.AddedTotalRequests()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TunnelTrafficLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case tunneltrafficlog.FieldBytesIn:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddBytesIn(v)
		return nil
	case tunneltrafficlog.FieldBytesOut:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddBytesOut(v)
		return nil
	case tunneltrafficlog.FieldTotalRequests:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTotalRequests(v)
		return nil
	}
	return fmt.Errorf("unknown TunnelTrafficLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TunnelTrafficLogMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TunnelTrafficLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TunnelTrafficLogMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TunnelTrafficLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TunnelTrafficLogMutation) ResetField(name string) error {
	switch name {
	case tunneltrafficlog.FieldTunnelID:
		m.ResetTunnelID()
		return nil
	case tunneltrafficlog.FieldBytesIn:
		m.ResetBytesIn()
		return nil
	case tunneltrafficlog.FieldBytesOut:
		m.ResetBytesOut()
		return nil
	case tunneltrafficlog.FieldTotalRequests:
		m.ResetTotalRequests()
		return nil
	case tunneltrafficlog.FieldRecordedAt:
		m.ResetRecordedAt()
		return nil
	}
	return fmt.Errorf("unknown TunnelTrafficLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TunnelTrafficLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.user != nil {
		edges = append(edges, tunneltrafficlog.EdgeUser)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TunnelTrafficLogMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case tunneltrafficlog.EdgeUser:
		if id := m.user; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TunnelTrafficLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TunnelTrafficLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TunnelTrafficLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleareduser {
		edges = append(edges, tunneltrafficlog.EdgeUser)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TunnelTrafficLogMutation) EdgeCleared(name string) bool {
	switch name {
	case tunneltrafficlog.EdgeUser:
		return m.cleareduser
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TunnelTrafficLogMutation) ClearEdge(name string) error {
	switch name {
	case tunneltrafficlog.EdgeUser:
		m.ClearUser()
		return nil
	}
	return fmt.Errorf("unknown TunnelTrafficLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TunnelTrafficLogMutation) ResetEdge(name string) error {
	switch name {
	case tunneltrafficlog.EdgeUser:
		m.ResetUser()
		return nil
	}
	return fmt.Errorf("unknown TunnelTrafficLog edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int64
	nickname            *string
	username            *string
	password            *string
	email               *string
	clearedFields       map[string]struct{}
	credentials         map[int64]struct{}
	removedcredentials  map[int64]struct{}
	clearedcredentials  bool
	traffic_logs        map[int64]struct{}
	removedtraffic_logs map[int64]struct{}
	clearedtraffic_logs bool
	done                bool
	oldValue            func(context.Context) (*User, error)
	predicates          []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int64) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNickname sets the "nickname" field.
func (m *UserMutation) SetNickname(s string) {
	m.nickname = &s
}

// Nickname returns the value of the "nickname" field in the mutation.
func (m *UserMutation) Nickname() (r string, exists bool) {
	v := m.nickname
	if v == nil {
		return
	}
	return *v, true
}

// OldNickname returns the old "nickname" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldNickname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNickname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNickname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNickname: %w", err)
	}
	return oldValue.Nickname, nil
}

// ResetNickname resets all changes to the "nickname" field.
func (m *UserMutation) ResetNickname() {
	m.nickname = nil
}

// SetUsername sets the "username" field.
func (m *UserMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *UserMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *UserMutation) ResetUsername() {
	m.username = nil
}

// SetPassword sets the "password" field.
func (m *UserMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the value of the "password" field in the mutation.
func (m *UserMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword resets all changes to the "password" field.
func (m *UserMutation) ResetPassword() {
	m.password = nil
}

// SetEmail sets the "email" field.
func (m *UserMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *UserMutation) ResetEmail() {
	m.email = nil
}

// AddCredentialIDs adds the "credentials" edge to the Credential entity by ids.
func (m *UserMutation) AddCredentialIDs(ids ...int64) {
	if m.credentials == nil {
		m.credentials = make(map[int64]struct{})
	}
	for i := range ids {
		m.credentials[ids[i]] = struct{}{}
	}
}

// ClearCredentials clears the "credentials" edge to the Credential entity.
func (m *UserMutation) ClearCredentials() {
	m.clearedcredentials = true
}

// CredentialsCleared reports if the "credentials" edge to the Credential entity was cleared.
func (m *UserMutation) CredentialsCleared() bool {
	return m.clearedcredentials
}

// RemoveCredentialIDs removes the "credentials" edge to the Credential entity by IDs.
func (m *UserMutation) RemoveCredentialIDs(ids ...int64) {
	if m.removedcredentials == nil {
		m.removedcredentials = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.credentials, ids[i])
		m.removedcredentials[ids[i]] = struct{}{}
	}
}

// RemovedCredentials returns the removed IDs of the "credentials" edge to the Credential entity.
func (m *UserMutation) RemovedCredentialsIDs() (ids []int64) {
	for id := range m.removedcredentials {
		ids = append(ids, id)
	}
	return
}

// CredentialsIDs returns the "credentials" edge IDs in the mutation.
func (m *UserMutation) CredentialsIDs() (ids []int64) {
	for id := range m.credentials {
		ids = append(ids, id)
	}
	return
}

// ResetCredentials resets all changes to the "credentials" edge.
func (m *UserMutation) ResetCredentials() {
	m.credentials = nil
	m.clearedcredentials = false
	m.removedcredentials = nil
}

// AddTrafficLogIDs adds the "traffic_logs" edge to the TunnelTrafficLog entity by ids.
func (m *UserMutation) AddTrafficLogIDs(ids ...int64) {
	if m.traffic_logs == nil {
		m.traffic_logs = make(map[int64]struct{})
	}
	for i := range ids {
		m.traffic_logs[ids[i]] = struct{}{}
	}
}

// ClearTrafficLogs clears the "traffic_logs" edge to the TunnelTrafficLog entity.
func (m *UserMutation) ClearTrafficLogs() {
	m.clearedtraffic_logs = true
}

// TrafficLogsCleared reports if the "traffic_logs" edge to the TunnelTrafficLog entity was cleared.
func (m *UserMutation) TrafficLogsCleared() bool {
	return m.clearedtraffic_logs
}

// RemoveTrafficLogIDs removes the "traffic_logs" edge to the TunnelTrafficLog entity by IDs.
func (m *UserMutation) RemoveTrafficLogIDs(ids ...int64) {
	if m.removedtraffic_logs == nil {
		m.removedtraffic_logs = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.traffic_logs, ids[i])
		m.removedtraffic_logs[ids[i]] = struct{}{}
	}
}

// RemovedTrafficLogs returns the removed IDs of the "traffic_logs" edge to the TunnelTrafficLog entity.
func (m *UserMutation) RemovedTrafficLogsIDs() (ids []int64) {
	for id := range m.removedtraffic_logs {
		ids = append(ids, id)
	}
	return
}

// TrafficLogsIDs returns the "traffic_logs" edge IDs in the mutation.
func (m *UserMutation) TrafficLogsIDs() (ids []int64) {
	for id := range m.traffic_logs {
		ids = append(ids, id)
	}
	return
}

// ResetTrafficLogs resets all changes to the "traffic_logs" edge.
func (m *UserMutation) ResetTrafficLogs() {
	m.traffic_logs = nil
	m.clearedtraffic_logs = false
	m.removedtraffic_logs = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.nickname != nil {
		fields = append(fields, user.FieldNickname)
	}
	if m.username != nil {
		fields = append(fields, user.FieldUsername)
	}
	if m.password != nil {
		fields = append(fields, user.FieldPassword)
	}
	if m.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldNickname:
		return m.Nickname()
	case user.FieldUsername:
		return m.Username()
	case user.FieldPassword:
		return m.Password()
	case user.FieldEmail:
		return m.Email()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldNickname:
		return m.OldNickname(ctx)
	case user.FieldUsername:
		return m.OldUsername(ctx)
	case user.FieldPassword:
		return m.OldPassword(ctx)
	case user.FieldEmail:
		return m.OldEmail(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldNickname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNickname(v)
		return nil
	case user.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case user.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldNickname:
		m.ResetNickname()
		return nil
	case user.FieldUsername:
		m.ResetUsername()
		return nil
	case user.FieldPassword:
		m.ResetPassword()
		return nil
	case user.FieldEmail:
		m.ResetEmail()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.credentials != nil {
		edges = append(edges, user.EdgeCredentials)
	}
	if m.traffic_logs != nil {
		edges = append(edges, user.EdgeTrafficLogs)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeCredentials:
		ids := make([]ent.Value, 0, len(m.credentials))
		for id := range m.credentials {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeTrafficLogs:
		ids := make([]ent.Value, 0, len(m.traffic_logs))
		for id := range m.traffic_logs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedcredentials != nil {
		edges = append(edges, user.EdgeCredentials)
	}
	if m.removedtraffic_logs != nil {
		edges = append(edges, user.EdgeTrafficLogs)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeCredentials:
		ids := make([]ent.Value, 0, len(m.removedcredentials))
		for id := range m.removedcredentials {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeTrafficLogs:
		ids := make([]ent.Value, 0, len(m.removedtraffic_logs))
		for id := range m.removedtraffic_logs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedcredentials {
		edges = append(edges, user.EdgeCredentials)
	}
	if m.clearedtraffic_logs {
		edges = append(edges, user.EdgeTrafficLogs)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeCredentials:
		return m.clearedcredentials
	case user.EdgeTrafficLogs:
		return m.clearedtraffic_logs
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeCredentials:
		m.ResetCredentials()
		return nil
	case user.EdgeTrafficLogs:
		m.ResetTrafficLogs()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
