// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/predicate"
	"cloudflared-tunnel/ent/tunneltrafficlog"
	"cloudflared-tunnel/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TunnelTrafficLogUpdate is the builder for updating TunnelTrafficLog entities.
type TunnelTrafficLogUpdate struct {
	config
	hooks    []Hook
	mutation *TunnelTrafficLogMutation
}

// Where appends a list predicates to the TunnelTrafficLogUpdate builder.
func (_u *TunnelTrafficLogUpdate) Where(ps ...predicate.TunnelTrafficLog) *TunnelTrafficLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTunnelID sets the "tunnel_id" field.
func (_u *TunnelTrafficLogUpdate) SetTunnelID(v string) *TunnelTrafficLogUpdate {
	_u.mutation.SetTunnelID(v)
	return _u
}

// SetNillableTunnelID sets the "tunnel_id" field if the given value is not nil.
func (_u *TunnelTrafficLogUpdate) SetNillableTunnelID(v *string) *TunnelTrafficLogUpdate {
	if v != nil {
		_u.SetTunnelID(*v)
	}
	return _u
}

// SetBytesIn sets the "bytes_in" field.
func (_u *TunnelTrafficLogUpdate) SetBytesIn(v int64) *TunnelTrafficLogUpdate {
	_u.mutation.ResetBytesIn()
	_u.mutation.SetBytesIn(v)
	return _u
}

// SetNillableBytesIn sets the "bytes_in" field if the given value is not nil.
func (_u *TunnelTrafficLogUpdate) SetNillableBytesIn(v *int64) *TunnelTrafficLogUpdate {
	if v != nil {
		_u.SetBytesIn(*v)
	}
	return _u
}

// AddBytesIn adds value to the "bytes_in" field.
func (_u *TunnelTrafficLogUpdate) AddBytesIn(v int64) *TunnelTrafficLogUpdate {
	_u.mutation.AddBytesIn(v)
	return _u
}

// SetBytesOut sets the "bytes_out" field.
func (_u *TunnelTrafficLogUpdate) SetBytesOut(v int64) *TunnelTrafficLogUpdate {
	_u.mutation.ResetBytesOut()
	_u.mutation.SetBytesOut(v)
	return _u
}

// SetNillableBytesOut sets the "bytes_out" field if the given value is not nil.
func (_u *TunnelTrafficLogUpdate) SetNillableBytesOut(v *int64) *TunnelTrafficLogUpdate {
	if v != nil {
		_u.SetBytesOut(*v)
	}
	return _u
}

// AddBytesOut adds value to the "bytes_out" field.
func (_u *TunnelTrafficLogUpdate) AddBytesOut(v int64) *TunnelTrafficLogUpdate {
	_u.mutation.AddBytesOut(v)
	return _u
}

// SetTotalRequests sets the "total_requests" field.
func (_u *TunnelTrafficLogUpdate) SetTotalRequests(v int64) *TunnelTrafficLogUpdate {
	_u.mutation.ResetTotalRequests()
	_u.mutation.SetTotalRequests(v)
	return _u
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_u *TunnelTrafficLogUpdate) SetNillableTotalRequests(v *int64) *TunnelTrafficLogUpdate {
	if v != nil {
		_u.SetTotalRequests(*v)
	}
	return _u
}

// AddTotalRequests adds value to the "total_requests" field.
func (_u *TunnelTrafficLogUpdate) AddTotalRequests(v int64) *TunnelTrafficLogUpdate {
	_u.mutation.AddTotalRequests(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *TunnelTrafficLogUpdate) SetUserID(id int64) *TunnelTrafficLogUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TunnelTrafficLogUpdate) SetUser(v *User) *TunnelTrafficLogUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TunnelTrafficLogMutation object of the builder.
func (_u *TunnelTrafficLogUpdate) Mutation() *TunnelTrafficLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TunnelTrafficLogUpdate) ClearUser() *TunnelTrafficLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TunnelTrafficLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelTrafficLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TunnelTrafficLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelTrafficLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelTrafficLogUpdate) check() error {
	if v, ok := _u.mutation.TunnelID(); ok {
		if err := tunneltrafficlog.TunnelIDValidator(v); err != nil {
			return &ValidationError{Name: "tunnel_id", err: fmt.Errorf(`ent: validator failed for field "TunnelTrafficLog.tunnel_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TunnelTrafficLog.user"`)
	}
	return nil
}

func (_u *TunnelTrafficLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunneltrafficlog.Table, tunneltrafficlog.Columns, sqlgraph.NewFieldSpec(tunneltrafficlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TunnelID(); ok {
		_spec.SetField(tunneltrafficlog.FieldTunnelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BytesIn(); ok {
		_spec.SetField(tunneltrafficlog.FieldBytesIn, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytesIn(); ok {
		_spec.AddField(tunneltrafficlog.FieldBytesIn, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BytesOut(); ok {
		_spec.SetField(tunneltrafficlog.FieldBytesOut, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytesOut(); ok {
		_spec.AddField(tunneltrafficlog.FieldBytesOut, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalRequests(); ok {
		_spec.SetField(tunneltrafficlog.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRequests(); ok {
		_spec.AddField(tunneltrafficlog.FieldTotalRequests, field.TypeInt64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tunneltrafficlog.UserTable,
			Columns: []string{tunneltrafficlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tunneltrafficlog.UserTable,
			Columns: []string{tunneltrafficlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunneltrafficlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TunnelTrafficLogUpdateOne is the builder for updating a single TunnelTrafficLog entity.
type TunnelTrafficLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TunnelTrafficLogMutation
}

// SetTunnelID sets the "tunnel_id" field.
func (_u *TunnelTrafficLogUpdateOne) SetTunnelID(v string) *TunnelTrafficLogUpdateOne {
	_u.mutation.SetTunnelID(v)
	return _u
}

// SetNillableTunnelID sets the "tunnel_id" field if the given value is not nil.
func (_u *TunnelTrafficLogUpdateOne) SetNillableTunnelID(v *string) *TunnelTrafficLogUpdateOne {
	if v != nil {
		_u.SetTunnelID(*v)
	}
	return _u
}

// SetBytesIn sets the "bytes_in" field.
func (_u *TunnelTrafficLogUpdateOne) SetBytesIn(v int64) *TunnelTrafficLogUpdateOne {
	_u.mutation.ResetBytesIn()
	_u.mutation.SetBytesIn(v)
	return _u
}

// SetNillableBytesIn sets the "bytes_in" field if the given value is not nil.
func (_u *TunnelTrafficLogUpdateOne) SetNillableBytesIn(v *int64) *TunnelTrafficLogUpdateOne {
	if v != nil {
		_u.SetBytesIn(*v)
	}
	return _u
}

// AddBytesIn adds value to the "bytes_in" field.
func (_u *TunnelTrafficLogUpdateOne) AddBytesIn(v int64) *TunnelTrafficLogUpdateOne {
	_u.mutation.AddBytesIn(v)
	return _u
}

// SetBytesOut sets the "bytes_out" field.
func (_u *TunnelTrafficLogUpdateOne) SetBytesOut(v int64) *TunnelTrafficLogUpdateOne {
	_u.mutation.ResetBytesOut()
	_u.mutation.SetBytesOut(v)
	return _u
}

// SetNillableBytesOut sets the "bytes_out" field if the given value is not nil.
func (_u *TunnelTrafficLogUpdateOne) SetNillableBytesOut(v *int64) *TunnelTrafficLogUpdateOne {
	if v != nil {
		_u.SetBytesOut(*v)
	}
	return _u
}

// AddBytesOut adds value to the "bytes_out" field.
func (_u *TunnelTrafficLogUpdateOne) AddBytesOut(v int64) *TunnelTrafficLogUpdateOne {
	_u.mutation.AddBytesOut(v)
	return _u
}

// SetTotalRequests sets the "total_requests" field.
func (_u *TunnelTrafficLogUpdateOne) SetTotalRequests(v int64) *TunnelTrafficLogUpdateOne {
	_u.mutation.ResetTotalRequests()
	_u.mutation.SetTotalRequests(v)
	return _u
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_u *TunnelTrafficLogUpdateOne) SetNillableTotalRequests(v *int64) *TunnelTrafficLogUpdateOne {
	if v != nil {
		_u.SetTotalRequests(*v)
	}
	return _u
}

// AddTotalRequests adds value to the "total_requests" field.
func (_u *TunnelTrafficLogUpdateOne) AddTotalRequests(v int64) *TunnelTrafficLogUpdateOne {
	_u.mutation.AddTotalRequests(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *TunnelTrafficLogUpdateOne) SetUserID(id int64) *TunnelTrafficLogUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TunnelTrafficLogUpdateOne) SetUser(v *User) *TunnelTrafficLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TunnelTrafficLogMutation object of the builder.
func (_u *TunnelTrafficLogUpdateOne) Mutation() *TunnelTrafficLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TunnelTrafficLogUpdateOne) ClearUser() *TunnelTrafficLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TunnelTrafficLogUpdate builder.
func (_u *TunnelTrafficLogUpdateOne) Where(ps ...predicate.TunnelTrafficLog) *TunnelTrafficLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TunnelTrafficLogUpdateOne) Select(field string, fields ...string) *TunnelTrafficLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TunnelTrafficLog entity.
func (_u *TunnelTrafficLogUpdateOne) Save(ctx context.Context) (*TunnelTrafficLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelTrafficLogUpdateOne) SaveX(ctx context.Context) *TunnelTrafficLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TunnelTrafficLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelTrafficLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelTrafficLogUpdateOne) check() error {
	if v, ok := _u.mutation.TunnelID(); ok {
		if err := tunneltrafficlog.TunnelIDValidator(v); err != nil {
			return &ValidationError{Name: "tunnel_id", err: fmt.Errorf(`ent: validator failed for field "TunnelTrafficLog.tunnel_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TunnelTrafficLog.user"`)
	}
	return nil
}

func (_u *TunnelTrafficLogUpdateOne) sqlSave(ctx context.Context) (_node *TunnelTrafficLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunneltrafficlog.Table, tunneltrafficlog.Columns, sqlgraph.NewFieldSpec(tunneltrafficlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TunnelTrafficLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tunneltrafficlog.FieldID)
		for _, f := range fields {
			if !tunneltrafficlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tunneltrafficlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TunnelID(); ok {
		_spec.SetField(tunneltrafficlog.FieldTunnelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BytesIn(); ok {
		_spec.SetField(tunneltrafficlog.FieldBytesIn, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytesIn(); ok {
		_spec.AddField(tunneltrafficlog.FieldBytesIn, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BytesOut(); ok {
		_spec.SetField(tunneltrafficlog.FieldBytesOut, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytesOut(); ok {
		_spec.AddField(tunneltrafficlog.FieldBytesOut, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalRequests(); ok {
		_spec.SetField(tunneltrafficlog.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRequests(); ok {
		_spec.AddField(tunneltrafficlog.FieldTotalRequests, field.TypeInt64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tunneltrafficlog.UserTable,
			Columns: []string{tunneltrafficlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tunneltrafficlog.UserTable,
			Columns: []string{tunneltrafficlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TunnelTrafficLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunneltrafficlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
