// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/predicate"
	"cloudflared-tunnel/ent/tunneltrafficlog"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TunnelTrafficLogDelete is the builder for deleting a TunnelTrafficLog entity.
type TunnelTrafficLogDelete struct {
	config
	hooks    []Hook
	mutation *TunnelTrafficLogMutation
}

// Where appends a list predicates to the TunnelTrafficLogDelete builder.
func (_d *TunnelTrafficLogDelete) Where(ps ...predicate.TunnelTrafficLog) *TunnelTrafficLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TunnelTrafficLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TunnelTrafficLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TunnelTrafficLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tunneltrafficlog.Table, sqlgraph.NewFieldSpec(tunneltrafficlog.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TunnelTrafficLogDeleteOne is the builder for deleting a single TunnelTrafficLog entity.
type TunnelTrafficLogDeleteOne struct {
	_d *TunnelTrafficLogDelete
}

// Where appends a list predicates to the TunnelTrafficLogDelete builder.
func (_d *TunnelTrafficLogDeleteOne) Where(ps ...predicate.TunnelTrafficLog) *TunnelTrafficLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TunnelTrafficLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tunneltrafficlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TunnelTrafficLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
