// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/tunneltrafficlog"
	"cloudflared-tunnel/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TunnelTrafficLogCreate is the builder for creating a TunnelTrafficLog entity.
type TunnelTrafficLogCreate struct {
	config
	mutation *TunnelTrafficLogMutation
	hooks    []Hook
}

// SetTunnelID sets the "tunnel_id" field.
func (_c *TunnelTrafficLogCreate) SetTunnelID(v string) *TunnelTrafficLogCreate {
	_c.mutation.SetTunnelID(v)
	return _c
}

// SetBytesIn sets the "bytes_in" field.
func (_c *TunnelTrafficLogCreate) SetBytesIn(v int64) *TunnelTrafficLogCreate {
	_c.mutation.SetBytesIn(v)
	return _c
}

// SetNillableBytesIn sets the "bytes_in" field if the given value is not nil.
func (_c *TunnelTrafficLogCreate) SetNillableBytesIn(v *int64) *TunnelTrafficLogCreate {
	if v != nil {
		_c.SetBytesIn(*v)
	}
	return _c
}

// SetBytesOut sets the "bytes_out" field.
func (_c *TunnelTrafficLogCreate) SetBytesOut(v int64) *TunnelTrafficLogCreate {
	_c.mutation.SetBytesOut(v)
	return _c
}

// SetNillableBytesOut sets the "bytes_out" field if the given value is not nil.
func (_c *TunnelTrafficLogCreate) SetNillableBytesOut(v *int64) *TunnelTrafficLogCreate {
	if v != nil {
		_c.SetBytesOut(*v)
	}
	return _c
}

// SetTotalRequests sets the "total_requests" field.
func (_c *TunnelTrafficLogCreate) SetTotalRequests(v int64) *TunnelTrafficLogCreate {
	_c.mutation.SetTotalRequests(v)
	return _c
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_c *TunnelTrafficLogCreate) SetNillableTotalRequests(v *int64) *TunnelTrafficLogCreate {
	if v != nil {
		_c.SetTotalRequests(*v)
	}
	return _c
}

// SetRecordedAt sets the "recorded_at" field.
func (_c *TunnelTrafficLogCreate) SetRecordedAt(v time.Time) *TunnelTrafficLogCreate {
	_c.mutation.SetRecordedAt(v)
	return _c
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_c *TunnelTrafficLogCreate) SetNillableRecordedAt(v *time.Time) *TunnelTrafficLogCreate {
	if v != nil {
		_c.SetRecordedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TunnelTrafficLogCreate) SetID(v int64) *TunnelTrafficLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *TunnelTrafficLogCreate) SetUserID(id int64) *TunnelTrafficLogCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TunnelTrafficLogCreate) SetUser(v *User) *TunnelTrafficLogCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TunnelTrafficLogMutation object of the builder.
func (_c *TunnelTrafficLogCreate) Mutation() *TunnelTrafficLogMutation {
	return _c.mutation
}

// Save creates the TunnelTrafficLog in the database.
func (_c *TunnelTrafficLogCreate) Save(ctx context.Context) (*TunnelTrafficLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TunnelTrafficLogCreate) SaveX(ctx context.Context) *TunnelTrafficLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TunnelTrafficLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TunnelTrafficLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TunnelTrafficLogCreate) defaults() {
	if _, ok := _c.mutation.BytesIn(); !ok {
		v := tunneltrafficlog.DefaultBytesIn
		_c.mutation.SetBytesIn(v)
	}
	if _, ok := _c.mutation.BytesOut(); !ok {
		v := tunneltrafficlog.DefaultBytesOut
		_c.mutation.SetBytesOut(v)
	}
	if _, ok := _c.mutation.TotalRequests(); !ok {
		v := tunneltrafficlog.DefaultTotalRequests
		_c.mutation.SetTotalRequests(v)
	}
	if _, ok := _c.mutation.RecordedAt(); !ok {
		v := tunneltrafficlog.DefaultRecordedAt()
		_c.mutation.SetRecordedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TunnelTrafficLogCreate) check() error {
	if _, ok := _c.mutation.TunnelID(); !ok {
		return &ValidationError{Name: "tunnel_id", err: errors.New(`ent: missing required field "TunnelTrafficLog.tunnel_id"`)}
	}
	if v, ok := _c.mutation.TunnelID(); ok {
		if err := tunneltrafficlog.TunnelIDValidator(v); err != nil {
			return &ValidationError{Name: "tunnel_id", err: fmt.Errorf(`ent: validator failed for field "TunnelTrafficLog.tunnel_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BytesIn(); !ok {
		return &ValidationError{Name: "bytes_in", err: errors.New(`ent: missing required field "TunnelTrafficLog.bytes_in"`)}
	}
	if _, ok := _c.mutation.BytesOut(); !ok {
		return &ValidationError{Name: "bytes_out", err: errors.New(`ent: missing required field "TunnelTrafficLog.bytes_out"`)}
	}
	if _, ok := _c.mutation.TotalRequests(); !ok {
		return &ValidationError{Name: "total_requests", err: errors.New(`ent: missing required field "TunnelTrafficLog.total_requests"`)}
	}
	if _, ok := _c.mutation.RecordedAt(); !ok {
		return &ValidationError{Name: "recorded_at", err: errors.New(`ent: missing required field "TunnelTrafficLog.recorded_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := tunneltrafficlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TunnelTrafficLog.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TunnelTrafficLog.user"`)}
	}
	return nil
}

func (_c *TunnelTrafficLogCreate) sqlSave(ctx context.Context) (*TunnelTrafficLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TunnelTrafficLogCreate) createSpec() (*TunnelTrafficLog, *sqlgraph.CreateSpec) {
	var (
		_node = &TunnelTrafficLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tunneltrafficlog.Table, sqlgraph.NewFieldSpec(tunneltrafficlog.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TunnelID(); ok {
		_spec.SetField(tunneltrafficlog.FieldTunnelID, field.TypeString, value)
		_node.TunnelID = value
	}
	if value, ok := _c.mutation.BytesIn(); ok {
		_spec.SetField(tunneltrafficlog.FieldBytesIn, field.TypeInt64, value)
		_node.BytesIn = value
	}
	if value, ok := _c.mutation.BytesOut(); ok {
		_spec.SetField(tunneltrafficlog.FieldBytesOut, field.TypeInt64, value)
		_node.BytesOut = value
	}
	if value, ok := _c.mutation.TotalRequests(); ok {
		_spec.SetField(tunneltrafficlog.FieldTotalRequests, field.TypeInt64, value)
		_node.TotalRequests = value
	}
	if value, ok := _c.mutation.RecordedAt(); ok {
		_spec.SetField(tunneltrafficlog.FieldRecordedAt, field.TypeTime, value)
		_node.RecordedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tunneltrafficlog.UserTable,
			Columns: []string{tunneltrafficlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_traffic_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TunnelTrafficLogCreateBulk is the builder for creating many TunnelTrafficLog entities in bulk.
type TunnelTrafficLogCreateBulk struct {
	config
	err      error
	builders []*TunnelTrafficLogCreate
}

// Save creates the TunnelTrafficLog entities in the database.
func (_c *TunnelTrafficLogCreateBulk) Save(ctx context.Context) ([]*TunnelTrafficLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TunnelTrafficLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TunnelTrafficLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TunnelTrafficLogCreateBulk) SaveX(ctx context.Context) []*TunnelTrafficLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TunnelTrafficLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TunnelTrafficLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
