// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cloudflared-tunnel/ent/tunneltrafficlog"
	"cloudflared-tunnel/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TunnelTrafficLog is the model entity for the TunnelTrafficLog schema.
type TunnelTrafficLog struct {
	config `json:"-"`
	// ID of the ent.
	// 记录ID
	ID int64 `json:"id,omitempty"`
	// 隧道ID
	TunnelID string `json:"tunnel_id,omitempty"`
	// 入站字节数
	BytesIn int64 `json:"bytes_in,omitempty"`
	// 出站字节数
	BytesOut int64 `json:"bytes_out,omitempty"`
	// 总请求数
	TotalRequests int64 `json:"total_requests,omitempty"`
	// 记录时间
	RecordedAt time.Time `json:"recorded_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TunnelTrafficLogQuery when eager-loading is set.
	Edges             TunnelTrafficLogEdges `json:"edges"`
	user_traffic_logs *int64
	selectValues      sql.SelectValues
}

// TunnelTrafficLogEdges holds the relations/edges for other nodes in the graph.
type TunnelTrafficLogEdges struct {
	// 所属用户
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TunnelTrafficLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TunnelTrafficLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tunneltrafficlog.FieldID, tunneltrafficlog.FieldBytesIn, tunneltrafficlog.FieldBytesOut, tunneltrafficlog.FieldTotalRequests:
			values[i] = new(sql.NullInt64)
		case tunneltrafficlog.FieldTunnelID:
			values[i] = new(sql.NullString)
		case tunneltrafficlog.FieldRecordedAt:
			values[i] = new(sql.NullTime)
		case tunneltrafficlog.ForeignKeys[0]: // user_traffic_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TunnelTrafficLog fields.
func (_m *TunnelTrafficLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tunneltrafficlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case tunneltrafficlog.FieldTunnelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tunnel_id", values[i])
			} else if value.Valid {
				_m.TunnelID = value.String
			}
		case tunneltrafficlog.FieldBytesIn:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bytes_in", values[i])
			} else if value.Valid {
				_m.BytesIn = value.Int64
			}
		case tunneltrafficlog.FieldBytesOut:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bytes_out", values[i])
			} else if value.Valid {
				_m.BytesOut = value.Int64
			}
		case tunneltrafficlog.FieldTotalRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_requests", values[i])
			} else if value.Valid {
				_m.TotalRequests = value.Int64
			}
		case tunneltrafficlog.FieldRecordedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recorded_at", values[i])
			} else if value.Valid {
				_m.RecordedAt = value.Time
			}
		case tunneltrafficlog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_traffic_logs", value)
			} else if value.Valid {
				_m.user_traffic_logs = new(int64)
				*_m.user_traffic_logs = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TunnelTrafficLog.
// This includes values selected through modifiers, order, etc.
func (_m *TunnelTrafficLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the TunnelTrafficLog entity.
func (_m *TunnelTrafficLog) QueryUser() *UserQuery {
	return NewTunnelTrafficLogClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this TunnelTrafficLog.
// Note that you need to call TunnelTrafficLog.Unwrap() before calling this method if this TunnelTrafficLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TunnelTrafficLog) Update() *TunnelTrafficLogUpdateOne {
	return NewTunnelTrafficLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TunnelTrafficLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TunnelTrafficLog) Unwrap() *TunnelTrafficLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TunnelTrafficLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TunnelTrafficLog) String() string {
	var builder strings.Builder
	builder.WriteString("TunnelTrafficLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tunnel_id=")
	builder.WriteString(_m.TunnelID)
	builder.WriteString(", ")
	builder.WriteString("bytes_in=")
	builder.WriteString(fmt.Sprintf("%v", _m.BytesIn))
	builder.WriteString(", ")
	builder.WriteString("bytes_out=")
	builder.WriteString(fmt.Sprintf("%v", _m.BytesOut))
	builder.WriteString(", ")
	builder.WriteString("total_requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalRequests))
	builder.WriteString(", ")
	builder.WriteString("recorded_at=")
	builder.WriteString(_m.RecordedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TunnelTrafficLogs is a parsable slice of TunnelTrafficLog.
type TunnelTrafficLogs []*TunnelTrafficLog
