// Code generated by ent, DO NOT EDIT.

package credentialtestlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the credentialtestlog type in the database.
	Label = "credential_test_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldTestedAt holds the string denoting the tested_at field in the database.
	FieldTestedAt = "tested_at"
	// EdgeCredential holds the string denoting the credential edge name in mutations.
	EdgeCredential = "credential"
	// Table holds the table name of the credentialtestlog in the database.
	Table = "credential_test_logs"
	// CredentialTable is the table that holds the credential relation/edge.
	CredentialTable = "credential_test_logs"
	// CredentialInverseTable is the table name for the Credential entity.
	// It exists in this package in order to avoid circular dependency with the "credential" package.
	CredentialInverseTable = "credentials"
	// CredentialColumn is the table column denoting the credential relation/edge.
	CredentialColumn = "credential_test_logs"
)

// Columns holds all SQL columns for credentialtestlog fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldErrorMessage,
	FieldTestedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "credential_test_logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"credential_test_logs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultTestedAt holds the default value on creation for the "tested_at" field.
	DefaultTestedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the CredentialTestLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByTestedAt orders the results by the tested_at field.
func ByTestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTestedAt, opts...).ToFunc()
}

// ByCredentialField orders the results by credential field.
func ByCredentialField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCredentialStep(), sql.OrderByField(field, opts...))
	}
}
func newCredentialStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CredentialInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CredentialTable, CredentialColumn),
	)
}
