// Code generated by ent, DO NOT EDIT.

package credentialtestlog

import (
	"cloudflared-tunnel/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldLTE(FieldID, id))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldEQ(FieldStatus, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldEQ(FieldErrorMessage, v))
}

// TestedAt applies equality check predicate on the "tested_at" field. It's identical to TestedAtEQ.
func TestedAt(v time.Time) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldEQ(FieldTestedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// TestedAtEQ applies the EQ predicate on the "tested_at" field.
func TestedAtEQ(v time.Time) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldEQ(FieldTestedAt, v))
}

// TestedAtNEQ applies the NEQ predicate on the "tested_at" field.
func TestedAtNEQ(v time.Time) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldNEQ(FieldTestedAt, v))
}

// TestedAtIn applies the In predicate on the "tested_at" field.
func TestedAtIn(vs ...time.Time) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldIn(FieldTestedAt, vs...))
}

// TestedAtNotIn applies the NotIn predicate on the "tested_at" field.
func TestedAtNotIn(vs ...time.Time) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldNotIn(FieldTestedAt, vs...))
}

// TestedAtGT applies the GT predicate on the "tested_at" field.
func TestedAtGT(v time.Time) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldGT(FieldTestedAt, v))
}

// TestedAtGTE applies the GTE predicate on the "tested_at" field.
func TestedAtGTE(v time.Time) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldGTE(FieldTestedAt, v))
}

// TestedAtLT applies the LT predicate on the "tested_at" field.
func TestedAtLT(v time.Time) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldLT(FieldTestedAt, v))
}

// TestedAtLTE applies the LTE predicate on the "tested_at" field.
func TestedAtLTE(v time.Time) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.FieldLTE(FieldTestedAt, v))
}

// HasCredential applies the HasEdge predicate on the "credential" edge.
func HasCredential() predicate.CredentialTestLog {
	return predicate.CredentialTestLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CredentialTable, CredentialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCredentialWith applies the HasEdge predicate on the "credential" edge with a given conditions (other predicates).
func HasCredentialWith(preds ...predicate.Credential) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(func(s *sql.Selector) {
		step := newCredentialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CredentialTestLog) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CredentialTestLog) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CredentialTestLog) predicate.CredentialTestLog {
	return predicate.CredentialTestLog(sql.NotPredicates(p))
}
