// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CredentialsColumns holds the columns for the "credentials" table.
	CredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "凭证ID"},
		{Name: "name", Type: field.TypeString, Comment: "凭证名称"},
		{Name: "api_token", Type: field.TypeString, Comment: "加密后的 API Token"},
		{Name: "account_id", Type: field.TypeString, Comment: "Cloudflare Account ID"},
		{Name: "is_default", Type: field.TypeBool, Comment: "是否为默认凭证", Default: false},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "user_credentials", Type: field.TypeInt64},
	}
	// CredentialsTable holds the schema information for the "credentials" table.
	CredentialsTable = &schema.Table{
		Name:       "credentials",
		Columns:    CredentialsColumns,
		PrimaryKey: []*schema.Column{CredentialsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "credentials_users_credentials",
				Columns:    []*schema.Column{CredentialsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "credential_user_credentials",
				Unique:  false,
				Columns: []*schema.Column{CredentialsColumns[7]},
			},
		},
	}
	// CredentialTestLogsColumns holds the columns for the "credential_test_logs" table.
	CredentialTestLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "日志ID"},
		{Name: "status", Type: field.TypeString, Comment: "测试结果: success/failed"},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Comment: "错误信息"},
		{Name: "tested_at", Type: field.TypeTime, Comment: "测试时间"},
		{Name: "credential_test_logs", Type: field.TypeInt64},
	}
	// CredentialTestLogsTable holds the schema information for the "credential_test_logs" table.
	CredentialTestLogsTable = &schema.Table{
		Name:       "credential_test_logs",
		Columns:    CredentialTestLogsColumns,
		PrimaryKey: []*schema.Column{CredentialTestLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "credential_test_logs_credentials_test_logs",
				Columns:    []*schema.Column{CredentialTestLogsColumns[4]},
				RefColumns: []*schema.Column{CredentialsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TunnelTrafficLogsColumns holds the columns for the "tunnel_traffic_logs" table.
	TunnelTrafficLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "记录ID"},
		{Name: "tunnel_id", Type: field.TypeString, Comment: "隧道ID"},
		{Name: "bytes_in", Type: field.TypeInt64, Comment: "入站字节数", Default: 0},
		{Name: "bytes_out", Type: field.TypeInt64, Comment: "出站字节数", Default: 0},
		{Name: "total_requests", Type: field.TypeInt64, Comment: "总请求数", Default: 0},
		{Name: "recorded_at", Type: field.TypeTime, Comment: "记录时间"},
		{Name: "user_traffic_logs", Type: field.TypeInt64},
	}
	// TunnelTrafficLogsTable holds the schema information for the "tunnel_traffic_logs" table.
	TunnelTrafficLogsTable = &schema.Table{
		Name:       "tunnel_traffic_logs",
		Columns:    TunnelTrafficLogsColumns,
		PrimaryKey: []*schema.Column{TunnelTrafficLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tunnel_traffic_logs_users_traffic_logs",
				Columns:    []*schema.Column{TunnelTrafficLogsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tunneltrafficlog_tunnel_id_recorded_at",
				Unique:  false,
				Columns: []*schema.Column{TunnelTrafficLogsColumns[1], TunnelTrafficLogsColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "用户ID"},
		{Name: "nickname", Type: field.TypeString, Unique: true, Comment: "昵称"},
		{Name: "username", Type: field.TypeString, Unique: true, Comment: "用户名"},
		{Name: "password", Type: field.TypeString, Comment: "密码"},
		{Name: "email", Type: field.TypeString, Unique: true, Comment: "邮箱"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[2]},
			},
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CredentialsTable,
		CredentialTestLogsTable,
		TunnelTrafficLogsTable,
		UsersTable,
	}
)

func init() {
	CredentialsTable.ForeignKeys[0].RefTable = UsersTable
	CredentialsTable.Annotation = &entsql.Annotation{
		Table:   "credentials",
		Options: "COMMENT='Cloudflare 凭证表'",
	}
	CredentialTestLogsTable.ForeignKeys[0].RefTable = CredentialsTable
	CredentialTestLogsTable.Annotation = &entsql.Annotation{
		Table:   "credential_test_logs",
		Options: "COMMENT='凭证测试日志表'",
	}
	TunnelTrafficLogsTable.ForeignKeys[0].RefTable = UsersTable
	TunnelTrafficLogsTable.Annotation = &entsql.Annotation{
		Table:   "tunnel_traffic_logs",
		Options: "COMMENT='隧道流量统计记录表'",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table:   "users",
		Options: "COMMENT='用户表'",
	}
}
